### ISSUE TITLE
Use single metadata block for fixed-shaped variable

### ISSUE THREAD

**Issue by rtobar** [ornladios/ADIOS2#1165]
Hi,

For some time we have been doing some experiments with ADIOS2 as a I/O storage backend. While in principle it works fine, we have been experiencing a big file size overhead given the type of data we store.

In our data model we have a "column" composed of "cells". The latter have 2 dimensions. We use a single 3D ADIOS2 variable to store the column, and `adiosVar.Write` data into each of the cells with the appropriate Selection specification. Our Write calls are small though, amounting to a 4x1 array of single-precision complex values, for a total of 32 bytes. This creates a big overhead on the resulting BP files, which use about 20 times the storage that it would require if data were stored sequentially. When experimenting with using a simpler uni-dimensional 4-element array of complex values the overhead goes down to ~10x.

In our scenario the two inner dimensions sizes of our variable are always fixed. In principle users can continuously add data to our "column", but in practice we also set the outermost dimension size too to the max int value. Given this setup, it would be ideal to avoid hitting the penalty of writing metadata with each piece of data that gets written through `adiosVar.Write` with the BP File storage backend.

I tried using `constantDims = true` in the call to `IO.DefineVariable` thinking that this might have helped, only to learn later that this applies to all dimensions objects, including the variable selection, and not only to the shape.

**Comment by williamfgc** [comment]
@rtobar Let's provide some background first: we are an I/O streams library, we are moving your data as you wish. The "overhead" is because once out of your memory, we need to describe each block piece of memory for placement so the reader can understand it. We are not a memory placeholder framework like PETSc or Excel in which you pre-allocate and your memory is always alive until you deallocate, you're not constantly transporting it through a physical medium in that case.

> This creates a big overhead on the resulting BP files, which use about 20 times the storage that it would require if data were stored sequentially.

This is not the right "overhead", if you give adios a sequential piece of data, then we can measure adios overhead. A fair comparison would be saving each block of your data in another format in which each block comes in any order (independently) and trying to read it back as a continuous array (which is what adios is providing to you). It's like saving each cell independently (you need to save cell location) and opening it back as a table. 

> I tried using `constantDims = true` in the call to `IO.DefineVariable` thinking that this might have helped, only to learn later that this applies to all dimensions objects, including the variable selection, and not only to the shape.

Naming and docs are clear: constantDims, not constantShape. Chaging start and count (which is what SetSelection does effectively changes the dimensions given to adios, even though your shape might remain constant).

By no means ADIOS is perfect for this case, but takes me to the following alternatives: 

1. Today: Provide a memory placeholder for your data: not sure if you can do this, but that sounds to be the case for measuring the mentioned "overhead".
2. Near-future: ADIOS can provide the pre-allocated buffer memory, so users can populate data as they wish before they flush. This is not available yet, but it is in the plans for memory-bound applications. It's basically 1. from inside ADIOS. 

Hope this helps and clarifies things.

**Comment by JasonRuonanWang** [comment]
I will take this issue and see how DataMan format works on it

**Comment by williamfgc** [comment]
@JasonRuonanWang yes, please do. Thanks.

**Comment by williamfgc** [comment]
@rtobar I talked to @JasonRuonanWang offline about this, from my previous post:
`Near-future: ADIOS can provide the pre-allocated buffer memory, so users can populate data as they wish before they flush. `

This is now available in the current master. Allowing adios2 to pre-allocate larger memory blocks will reduce the size of the metadata (as less blocks are defined). Please feel free to start using it as this tackles the metadata problem you saw.
Working test:
https://github.com/ornladios/ADIOS2/blob/master/testing/adios2/engine/bp/TestBPWriteReadVariableSpan.cpp

**Comment by JasonRuonanWang** [comment]
This is fixed in the Table engine #1659.

It is a meta-engine that merges small data blocks across ranks and then puts them as larger blocks using BP4. The aggregation pattern is configurable through engine parameters so users can effectively control the metadata overheads.
