### ISSUE TITLE
bzip2 compression only for certain types?

### ISSUE THREAD

**Issue by germasch** [ornladios/ADIOS2#1208]
`DataManSerializer::IsCompressionAvailable()` contains this code, which may just have been copy&pasted from other compression methods.

```cxx
else if (method == "bzip2")
    {
      if (type == helper::GetType<int32_t>() || type == helper::GetType<int64_t>() ||
	  type == helper::GetType<float>() || type == helper::GetType<double>())
        {
            return true;
        }
    }
```
The other compression methods are lossy and constrain their types, but for all I'm aware, bzip2 is lossless, so I don't really see why it would need to be restricted to certain types?

This is certainly not a big issue, just something I saw along the way, so I thought I'd note it.

**Comment by williamfgc** [comment]
@germasch bzip2 dropped in our list of priorities, but will be there for the June release. DataManSerializer is maintained by @JasonRuonanWang

**Comment by JasonRuonanWang** [comment]
I got seg faults when trying signed char type with BZip2. I don't know if it's caused by the BZip2 library itself or how it is integrated into ADIOS2. But currently for DataMan serializer, limiting the types for BZip2 is the only way to work around.

**Comment by JasonRuonanWang** [comment]
The seg faults may be because the total number of bytes being compressed is too small in the tests, while the BZip2 library has bugs when dealing with very small size data chunks. I am not 100% sure about this. I am almost certain it's a BZip2 bug though. So given this has been tested with all relevant code and apps and proved to be stable. I will keep it as is at this point, to prevent introducing other problems by removing these limitations.

I can put this in my note and if BZip2 library is updated at some point then I can come back and re-try.

@germasch Thanks for raising this issue.
