### ISSUE TITLE
Open() in python bindings (example code, helloBPReaderHeatMap2D.py)

### ISSUE THREAD

**Issue by bsmind** [ornladios/ADIOS2#1246]
I cannot run the example code, `./examples/bpReader/helloBPReaderHeatMap2D.py`. 
When I run it, I got the following errors:
```
ibpStream = ioRead.Open('HeatMap2D_py.bp', adios2.Mode.Read. MPI.COMM_SELF)
TypeError: Open(): incompatible function arguments. The following argument types are supported:
     1. (self: adios2.IO, arg0: str, arg1: int) -> adios2::py11::Engine
```

When I looked at the `py11IO.h` file,
it has the following signature,
```
\#ifdef ADIOS2_HAVE_MPI
     Engine Open(const std::string &name, const Mode mode, MPI_Comm comm);
\#endif
```

I also checked the configured header file, `ADIOSConfig.h`, it has
```
\#define ADIOS2_HAVE_MPI
```

Any suggestions?

Thanks,
Sungsoo Ha

**Comment by germasch** [comment]
[Note: I'm not a team member here, just trying to be helpful.]

On your primary problem, I think you have the right idea, i.e, the Python interface you're using appears to be compiled without MPI support. Maybe you have an older version of ADIOS2 / its python bindings lying around that get picked up, rather than the current version, which appears to have picked up MPI correctly according to your `ADIOSConfig.h`? This might help to find out:
```python
>>> import adios2
>>> adios2.__file__
'/Users/kai/build/ADIOS2/build/lib/python3.7/site-packages/adios2.cpython-37m-darwin.so'
```

If you get this to work, you'll run into more trouble, because that example is out of date, and there is another problem in that the version of the `Open()` call with a communicator as last argument isn't properly supported. This makes it work for me: (partially similar to #1233)
```diff
diff --git a/examples/hello/bpReader/helloBPReaderHeatMap2D.py b/examples/hello/bpReader/helloBPReaderHeatMap2D.py
index 2c81b7bc9..8a7b94c77 100644
--- a/examples/hello/bpReader/helloBPReaderHeatMap2D.py
+++ b/examples/hello/bpReader/helloBPReaderHeatMap2D.py
@@ -41,9 +41,8 @@ for i in range(0, Nx):
 adios = adios2.ADIOS(comm)
 ioWrite = adios.DeclareIO("ioWriter")

-varTemperature = ioWrite.DefineVariable("temperature2D", shape,
-                                        start, count, adios2.ConstantDims,
-                                        temperatures)
+varTemperature = ioWrite.DefineVariable("temperature2D", temperatures, shape,
+                                        start, count, adios2.ConstantDims)

 obpStream = ioWrite.Open('HeatMap2D_py.bp', adios2.Mode.Write)
 obpStream.Put(varTemperature, temperatures)
@@ -53,7 +52,7 @@ obpStream.Close()
 if rank == 0:
     ioRead = adios.DeclareIO("ioReader")

-    ibpStream = ioRead.Open('HeatMap2D_py.bp', adios2.Mode.Read, MPI.COMM_SELF)
+    ibpStream = ioRead.Open('HeatMap2D_py.bp', adios2.Mode.Read)

     var_inTemperature = ioRead.InquireVariable("temperature2D")
```

**Comment by bsmind** [comment]
Thank you for your help.

First of all, there is only one version of ADIOS installed last week.  
```python
import adios2
adios2.__file__
'/opt/adios2/lib/python3.5/site-packages/adios2.cpython-35m-x86_64-linux-gnu.so'
```

Thank for pointing out the other problem that is in `DefineVariable`. I am also able to fix that part by changing the argument order.

For `OPen()`, I wonder why it couldn't take the third argument while it can run another function that is picked with MPI flag duing compilation, for example in `py11ADIOS.h`.
```c
\#ifdef ADIOS2_HAVE_API
     ADIOS(const std::string &configFile, MPI_Comm comm, const bool debugMode = true);
    ADIOS(MPI_Comm comm, const bool debugMode = true);
\#else
     ADIOS(const std::string &configFile, const bool debugMode = true);
    ADIOS(const bool debugMode = true);
\#endif
```
In the python, I could initialize adios with MPI_Comm argument.

I am not sure but I guess the error may be related to `py11glue.cpp`. In that file, under the IO class it only has one `def` for the `Open` signature that is only for the non-MPI mode (line 366).
```c
...
   .def("Open", (adios2::py11:Engine (adios2::py11::IO::*)(const std::string &, const int)) &adios2::py11::IO::Open)
...
```

**Comment by germasch** [comment]
> First of all, there is only one version of ADIOS installed last week.
> 
> ```python
> import adios2
> adios2.__file__
> '/opt/adios2/lib/python3.5/site-packages/adios2.cpython-35m-x86_64-linux-gnu.so'
> ```

Well, I'm out of guesses why you can't use `adios2.ADIOS(comm)`, then. It works for me. If I intentionally call it with wrong args, I get
```
TypeError: ADIOS(): incompatible function arguments. The following argument types are supported:
    1. (object: object, debugMode: bool=True) -> adios2::py11::ADIOS
    2. (configFile: str='', object: object, debugMode: bool=True) -> adios2::py11::ADIOS
```
which is what's expected when MPI is enabled.

> For `Open()`, I wonder why it couldn't take the third argument while it can run another function that is picked with MPI flag duing compilation, for example in `py11ADIOS.h`.

> I am not sure but I guess the error may be related to `py11glue.cpp`. In that file, under the IO class it only has one `def` for the `Open` signature that is only for the non-MPI mode (line 366).
> 
> ```c
> ...
>    .def("Open", (adios2::py11:Engine (adios2::py11::IO::*)(const std::string &, const int)) &adios2::py11::IO::Open)
> ...
> ```
Yes, I'm pretty sure that's the problem, the MPI variant of `Open` isn't registered. It's also broken because it doesn't actually use the communicator passed to it in its implementation. Fixing this shouldn't be too hard, but I believe since it takes the MPI communicator, one has to add in some additional wrapper code to convert the mpi4py communicator object to MPI_Comm, as done for other calls in `py11glue.cpp`.

**Comment by bsmind** [comment]
@germasch I have no problem in using `adios.ADIOS(comm)`. The problem is in calling `Open()` function with MPI argument. Thank for your help.

**Comment by williamfgc** [comment]
@bsmind I am guilty for not maintaining some things under examples, I am in the process of migrating some of those to a separate location. For a more robust example which run in our CI, please look under tests:  https://github.com/ornladios/ADIOS2/tree/master/testing/adios2/bindings/python

In any case, the Python low level bindings (they map C++) are not as popular as the more pythonic high-level ones with only require a single object (both can be found under the above link). The latter are suitable is you're trying to run analysis code outside an HPC cluster and performance is not a concern. The low-level APIs is needed for full features of ADIOS, but not without limitations (like the Open issue you brought up). 

The issue with passing a new MPI Comm at Open in the low-level APIs is related to early integration with previous PyBind11 version, passing the MPI_Comm would only work for plain functions, not member functions (that's why ADIOS is a function that mimics a constructor in glue). I'll double-check if this is something resolved so Open can be compatible with the C++ signature, we didn't pay much attention as this is the first time this is reported as an issue.

Hope this helps. Let me know if you have any more questions

**Comment by bsmind** [comment]
@williamfgc Thank for the comments with detailed information.
