### ISSUE TITLE
Span.Data() alignment

### ISSUE THREAD

**Issue by germasch** [ornladios/ADIOS2#1314]
I'm not sure you'll consider that a bug, but Variable::Span<T> will on my Mac return addresses that are aligned by 4 bytes only. While x86_64 can handle misaligned types, I believe in general the requirement is for malloc etc to return addresses aligned by 16 bytes on MacOS, Linux and Win64, so they can potentially be used with SSE2 etc.

**Comment by williamfgc** [comment]
@germasch if this becomes a problem we'll take a look. As far as I know (I haven't tested this), memcpy should be safe, but I don't know how each compiler handles this situation.

**Comment by germasch** [comment]
x86_64 handles misaligned access, except in certain (SSE2) contexts. I suppose Xeon Phi is similar. It's, however, not good for performance -- you might end up having a double sitting on two cache lines, even. memcpy of course is safe, but you're presumably handing the Span to the user so that they'll use it to calculate their output on the fly (ie., they'll actually access it as double, not via memcpy).

From [IBM](https://www.ibm.com/developerworks/library/pa-dalign/index.html):
> On the other hand, modern PowerPC processors lack hardware support for unaligned 64-bit floating-point access. When asked to load an unaligned floating-point number from memory, modern PowerPC processors will throw an exception and have the operating system perform the alignment chores in software. Performing alignment in software is much slower than performing it in hardware.

( I don't know if that applies to Summit, but I'd guess so.)

**Comment by germasch** [comment]
Just to be clear, I don't know if the lack of alignment is an actual issue, either performance wise or even correctness. (As an example,I believe SSE2 `movaps` can cause a segfault or bus error on unaligned data, but if no-one wants to use Span in that fashion, then it's not a problem.)

(I do think that users of Span are likely to use accesses in terms of the actual underlying data type, e.g., double. If one were just using it to memcpy to it, it'd seem much more straightforward to not use Span in the first place and have the memcpy happen in Put(Sync/Deferred). 

I also don't know whether the alignment is easily fixable. If BP3 can handle padding, it might be easy to fix this issue and return properly aligned buffers.

**Comment by eisenhauer** [comment]
Oy.  Thanks for the catch @germasch !  Unfortunately, I suspect that this may be a fatal flaw in the whole span concept.   (And I'm somewhat embarrassed I didn't think of it myself.  FFS jumps through incredible hoops to maintain a conservative guess about data alignment, even in its serialized form, because we want the application to be able to use memory directly from a receive buffer without copying it out.  I hate to think about the years of my life I probably spent on alignment issues and bugs.) To my knowledge, BP3 has never had a usage that might cause it to face anything like internal alignment requirements and I don't see anything in the BP3 serialization code that looks like it thinks about maintaining data alignment at all.  @pnorbert, can you verify this?  It looks to me like it's more of a "lets put stuff on the end of the buffer without regard to in-buffer alignment" sort of thing.  If so, then the memory region for any segment will be essentially randomly aligned, and while this sort of software-emulation of unaligned data references might still allow it to work (even if slowly) on some architectures, on others it will just blow up.  BP4 may be at an early enough stage that this could be addressed, but I'm guessing this is just not a reasonable thing for BP3...

**Comment by pnorbert** [comment]
Please note that BP3 was designed for C and file I/O with byte-level
access. Only using memcpy and POSIX IO and void* pointers. So naturally, we
have never encountered any issue with alignment. The initial buffer
allocation is indeed aligned, but not the starting position of a data array
coming from the user.

This may be the first oops moment since we decided we use the BP3 buffering
for most staging engines.

**Comment by eisenhauer** [comment]
Thanks for verifying @pnorbert.  I think to the extent that we can't guarantee data alignment for the data region in the buffer that the span feature was to provide access to, this is a show stopper.  At least until such a time as we might be moving everything to BP4 or some other marshaling scheme within which we could have different guarantees.  Do you concur?  If so, we might want to look at backing this stuff out of master...
