### ISSUE TITLE
Segmentation fault when setting MPI transportation method

### ISSUE THREAD

**Issue by khou2020** [ornladios/ADIOS2#1534]
I got segmentation fault calling adios2_open if i set transportation library tpo MPI.
Anyone klnow what happened?
 
`

    ad = adios2_init(MPI_COMM_WORLD, adios2_debug_mode_off);  

    io = adios2_declare_io(ad, "subarray");  

    err = adios2_set_engine(io, "BPFile"); 

    err = adios2_add_transport(&tid, io, "File"); 

    err = adios2_set_transport_parameter(io, tid, "Library", "MPI"); 

    eng = adios2_open(io, fname, adios2_mode_write);    // => Segmentation fault
`

**Comment by pnorbert** [comment]
I don't know why it segfaults instead of throwing a proper error, but there
is no transport called MPI in ADIOS2:

*Transport type: File*

*Key*

*Value Format*

*Default* and Examples

Library

string

*POSIX* (UNIX), *FStream* (Windows), stdio

https://adios2.readthedocs.io/en/latest/engines/engines.html?highlight=POSIX

**Comment by williamfgc** [comment]
@khou2020 A few things:

1. use `adios2_debug_mode_on` in `adios2_init` , check [adios2_init docs](https://adios2.readthedocs.io/en/latest/api_full/api_full.html#_CPPv411adios2_init8MPI_CommK17adios2_debug_mode)
2. "MPI" is not a supported value for "Library" in transport File, only "POSIX", "fstream" and "stdio".  Please, check your standard error output. 
3. Are you required to you use the C bindings, would using C++ APIs be an option? This is mainly due to safey.

In all honesty, we need to get better docs for the not-so-common API calls

**Comment by germasch** [comment]
I'm not sure it's the case here (that is, turning debug mode on leads to a proper error/exception), but I think generally, there are lots of places where sanity checks only happen when debug mode is on. Many of those are in cheap code paths (who cares about the cost of another if statement or two when opening a file), and I think it would be better to do those sanity checks no matter whether debug mode is on or off. I'd reserve debug mode only for expensive checks in hot code paths.

**Comment by williamfgc** [comment]
@germasch adios2 is a library, "cost" is never given by a library, it's only known by how it's invoked by the application inputs and calls frequency done to that library. Hence, "hot code" paths can't be known by the source code we distribute. We don't know N when searching in a O(log(N)) map, if N is too large debug_mode_off is an option to turn off "M" checks the users might do, once their workflow is stable. Ultimately we are talking about a simple bool flag the user if free to choose.

**Comment by williamfgc** [comment]
> I'm not sure it's the case here (that is, turning debug mode on leads to a proper error/exception), 

Not sure, I am following, are you reporting it's not throwing an exception? If so, would you mind opening a ticket?

**Comment by khou2020** [comment]
> @khou2020 A few things:
> 
> use adios2_debug_mode_on in adios2_init , check adios2_init docs  adios2_debug_mode_off is for static workflows (inputs won't change).
> "MPI" is not a supported value for "Library" in transport File, only "POSIX", "fstream" and "stdio".  Please, check your standard error output after turning adios2_debug_mode_on, and follow @pnorbert link to the docs.
> On a side note, are you required to you use the C bindings, would using the C++ APIs an option? This is mainly due to safety.
> 
> In all honesty, we need to get better docs for the not-so-common API calls

Thanks for the reply.
Does this mean ADIOS2 does not support MPI-IO supported in ADIOS 1.x? Is there a way to write to a single shared file only on metadata but also data?
Thanks

**Comment by williamfgc** [comment]
@khou2020 Thanks for reporting back. ADIOS2 doesn't support MPI-IO, nor can write a single metadata/data file. As an alternative you can set the number of substreams to 1. (This is the equivalent to aggregate in ADIOS1.x), but you end up with the metadata file `file.bp` and a single data file `file.bp.dir/file.bp.0` 

`adios2_set_parameter(io, "SubStreams", "1");`

For more parameters: see [BP3 parameters](https://adios2.readthedocs.io/en/latest/engines/engines.html#bp3-default)
