### ISSUE TITLE
SST: Memory leaks on reader disconnection

### ISSUE THREAD

**Issue by keichi** [ornladios/ADIOS2#1604]
While doing scalability tests with JAXA's workflow, I found that reconnecting the reader causes memory leaks. If I disconnect and connect the reader repeatedly, the memory footprint of the writers (except writer 0) keeps increasing. It seems that the queued timesteps are not being released when the reader disconnects. 

The engine parameters are: `RendezvousReaderCount=0`, `QueueLimit=2`, `QueueFullPolicy=Discard`. I'm seeing the same issue with gray-scott and pdf_calc as well, so I don't think it's an issue with JAXA's app or system.

**Comment by eisenhauer** [comment]
Thanks Keichi.  Currently our CI is unable to do dynamic analysis on anything test more complex than a single process, which unfortunately means that SST is largely uncovered, and manual testing probably hasn't tested the multiple-reader kill-and-reconnect situation.  I'll take a look and see what I can sort out.  (There are some memory items that SST leaves unfree'd until an entire stream closes because those addresses are used as reader IDs.  However those items should not be large.  If anything like a timestep is unfree'd, that's clearly unwarranted and unplanned.)

**Comment by eisenhauer** [comment]
Keichi, just looking for a little clarification.  I'm assuming that when you "disconnect" the reader, you're likely forcibly killing the reader rather than inducing a clean shutdown from the reader side (like reader_engine.Close()), right?  From what I can tell here using the SST KillReaders test as a baseline (modified to set QueueLimit:2,QueueFullPolicy:Discard), I'm not seeing leaks or delayed free()s of whole timesteps at the ADIOS2 level.  Using valgrind, what I *am* seeing are leaks that seem to be related to the failure of communication links.  Specifically, it looks like there are some EVPath-level resources being leaked on a writer as a one-time event when a reader fails.  So, leaks per reader failure, rather than per timestep, and while I'm seeing more than one, they're each relatively small (blocks < 1Kb) for a total in the 10s of Kbs.  (I haven't managed to excluded leaked MPI resources from my totals, so it's a little messy.)

So I wanted to ask exactly what level of memory increase that you're seeing.  Is it small enough to be explained by this sort of per-connection loss (and maybe the delayed free's I mention above)?

**Comment by keichi** [comment]
Thanks for looking into this, @eisenhauer.

> I'm assuming that when you "disconnect" the reader, you're likely forcibly killing the reader rather than inducing a clean shutdown from the reader side (like reader_engine.Close()), right?

You're right, I'm terminating the reader with Ctrl-C.

The memory increase we're seeing is significantly larger than KBs and is in the order of MBs to GBs. So I'm guessing the timestep data itself is not being free'd? Below is a plot I received from an engineer at JAXA (each line represents a compute node). You can see that the memory consumption does not decrease after the reader has disconnected.

![Screen Shot 2019-07-16 at 17 42 52](https://user-images.githubusercontent.com/791283/61283354-f9ba2f00-a7f7-11e9-9b05-b00325ce20a5.png)

**Comment by eisenhauer** [comment]
Hmm.  I probably have to reproduce this more exactly to see what is going on.  Can you send me command lines used to reproduce?  Maybe for the gray-scott example?   Whatever is happening, it doesn't seem to be happening in the simpler examples (KillReader test) where I'm trying to reproduce.

**Comment by keichi** [comment]
@eisenhauer I'm sorry, this might have been a bug in our app (EndStep was not called by the reader at each step). We will measure the memory consumption after the fix and get back to you.

**Comment by eisenhauer** [comment]
OK, let me know...    (And to be clear, you were calling BeginStep, but not EndStep?  If so, we should probably be throwing an exception on multiple calls to BeginStep...)

**Comment by keichi** [comment]
Yes, that's correct. Apparently, SstWriter checks unmatched BeginStep/EndStep, but SstReader doesn't.

**Comment by eisenhauer** [comment]
OK, let me add that as well...

**Comment by keichi** [comment]
It was indeed because of the missing EndStep() calls in our app. No memory leaks after we have added EndStep(). Closing this issue now.
