### ISSUE TITLE
InSituMPI AsyncSendVariable element type

### ISSUE THREAD

**Issue by bradking** [ornladios/ADIOS2#1664]
The code in `InSituMPIWriter::AsyncSendVariable` [here](https://github.com/ornladios/ADIOS2/blob/8008a10bb3eab1027c1d9bb1656ba4070dffc9af/source/adios2/engine/insitumpi/InSituMPIWriter.tcc#L134-L141) is:

```c++
const size_t blockStart = seek.first;
const size_t blockSize = seek.second - seek.first;

MPI_Isend(blockInfo.Data + blockStart, blockSize, MPI_CHAR,
```

The type of `blockInfo.Data` is `T` so `blockInfo.Data + blockStart` computes a buffer offset in multiples of `sizeof(T)`, but the size and element type use units of `sizeof(char)`.  This inconsistency is likely a bug.

**Comment by bradking** [comment]
Cc: @pnorbert

**Comment by pnorbert** [comment]
Interestingly, this is the "correct" way of doing it, but only because a
previous function call messes up those seek.first and seek.second values.
```
InsituMPISchedules.cpp:

void FixSeeksToZeroOffset(helper::SubFileInfo &record, bool isRowMajor)
noexcept
{
    size_t nElements = record.Seeks.second - record.Seeks.first + 1;
    size_t pos = helper::LinearIndex(record.BlockBox,
                                     record.IntersectionBox.first,
isRowMajor);
    record.Seeks.first = pos;
    record.Seeks.second = pos + nElements - 1;
}
```
At the input, Seeks are computed in bytes from PayloadOffset in files.
LinearIndex will compute in  elements of type T, so Seeks.first becomes a
value in sizeof(T)s, while Seeks.second is an ugly number, so that at the
code you point at,
seeks.second - seeks.first become the number of bytes that should be sent
over.

So this code is perfectly balanced with bugs. Luckily there is no
documentation of the struct where it would say what the size_t members
mean, so there is no contradiction there.

Moreover, this struct and functions around it are marked as deprecated and
they hang around only because we don't get around rewriting the insitumpi
engine.

**Comment by bradking** [comment]
Thanks for checking.  I'm fine with closing this.
