### ISSUE TITLE
Compression examples and shared-memory

### ISSUE THREAD

**Issue by tobiasrau** [ornladios/ADIOS2#1727]
Unfortunately, I couldn't find any examples on how to use the encoding or the shared memory implementation offered by ADIOS2.
Maybe I've just not found the right page in the documentation or in the examples of the repository.
However, it would be nice to get some more information about this topic.

**Comment by pnorbert** [comment]
Hi, can you please clarify what you mean by "encoding" and what you mean by
"shared-memory implementation". What are you looking for? At this point,
ADIOS2 does not have implementations or functionality named encoding or
named shared-memory anything. There is compression, and there is an inline
engine but I am not sure if that's what you are interested.

**Comment by tobiasrau** [comment]
Sorry for the unspecific question. With "encoding" I was aiming in the direction of compression (zfp, etc.). Are there examples available?
When ADIOS2 loads a file from shared-memory (/dev/shm) does it perform a mapping (zero-copy) or does it copy the content of the file? Is the user able to select a certain method?

**Comment by pnorbert** [comment]
Compression examples:
1. XML based set-up for runtime: 
examples/heatTransfer/heat_bp4_zfp.xml
```
    <io name="writer">
        <variable name="T">
            <operation type="zfp">
                <parameter key="accuracy" value="0.01"/>
            </operation>
        </variable>

        <engine type="BP4">
        </engine>
    </io>
```

2. Code based set-up for runtime: 
testing/adios2/engine/bp/operations/TestBPWriteReadZfp.cpp:60-73
testing/adios2/bindings/fortran/operation/TestBPWriteReadZfp2D.f90:88-110
testing/adios2/bindings/python/TestBPZfpHighLevelAPI.py:49-52

**Comment by germasch** [comment]
> When ADIOS2 loads a file from shared-memory (/dev/shm) does it perform a mapping (zero-copy) or does it copy the content of the file? Is the user able to select a certain method?

ADIOS2 uses POSIX I/O (or something basically built on top of it, like C stdio / C++ fstream) for reading / writing files on UNIX-like systems, it doesn't support `mmap`. So it doesn't support true zero-copy access.

**Comment by williamfgc** [comment]
@tobiasrau thanks for inquiring on the status of the usage of shared memory. Currently, our priority is to get the upcoming BP4 streaming format using typical heap buffering + POSIX I/O ready, as the majority of applications use this mechanism for file I/O. As for shared memory usage, we are refactoring the format functionality so it can be extended to memory buffers other than local heap. It's still work in progress, but we'll be happy to engage with you. The plan is to extent the existing current span signatures from write to read (which is what I understood as "mapping (zero-copy)" at read). Keep in mind that adios2 is selection based, so truly "zero-copy" is only available if the selected memory is fully contiguous. It gets more tricky with compressed data, since we need to decompress to get actual offsets. In a nutshell, the functionality is not one today, but we're working to enable it without any immediate need at the moment. Thanks!

**Comment by tobiasrau** [comment]
Thank you all for the quick and extensive answers. Compression is a nice tool for long-term storage of large data sets. But you are right, it does not combine well with a shared memory mapping. This was also not the plan. I'm looking forward for a shared memory mapping implementation in ADIOS2.
