### ISSUE TITLE
SST with one-side TCP

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#1957]
Trying to use SST between NERSC DTN (as a writer) and Cori compute node (as a reciever) but failed. I think the problem is caused when one side has no accessible address. I.e.,  
while DTN nodes have a public IP address, Cori computer node have no public IP address.  

@eisenhauer I remember there was technique called "reverse connection" or something like that to resolve such situation. Will it be difficult to add such function in SST?

Here is some information collected by using `sst_conn_tool` which I found very useful:

From the writer (DTN):
```
jyc@dtn03 delta-fusion (master) $ sst_conn_tool -i

	ADIOS2_IP_CONFIG best guess hostname is "dtn03.nersc.gov"
	ADIOS2_IP_CONFIG Possible interface lo : IPV4 127.0.0.1
	ADIOS2_IP_CONFIG Possible interface eth0 : IPV4 10.55.46.183
	ADIOS2_IP_CONFIG Possible interface ib100 : IPV4 10.100.107.103
	ADIOS2_IP_CONFIG Possible interface bond0 : IPV4 128.55.150.20
	ADIOS2_IP_CONFIG Possible interface bond1.136 : IPV4 128.55.136.20
	ADIOS2_IP_CONFIG Possible interface bond2.205 : IPV4 128.55.205.20
	ADIOS2_IP_CONFIG best guess IP is "128.55.205.20"
	ADIOS2_IP_CONFIG specified port range is "ANY" (unspecified)

 	The following environment variables can impact ADIOS2_IP_CONFIG operation:
		ADIOS2_IP  		-  Publish the specified IP address for contact
		ADIOS2_HOSTNAME  	-  Publish the specified hostname for contact
		ADIOS2_USE_HOSTNAME 	-  Publish a hostname preferentially over IP address
		ADIOS2_INTERFACE  	-  Use the IP address associated with the specified network interface
		ADIOS2_PORT_RANGE  	-  Use a port within the specified range "low:high",
		                 	   or specify "any" to let the OS choose

	Sst writer is listening for TCP/IP connection at IP 128.55.205.20, port 40764

	Sst connection tool waiting for connection...

Writer 0 (0x10299b0): Connection failed in SstInitWSReader! Contact list was:
Writer 0 (0x10299b0): AAMBAClXsP5pCYAKCF7/GGDqAAANb2leK7MAANWI344DAAAABQBlbmV0AAA=
Writer 0 (0x10299b0): Potential reader registration failed
```

From the Cori computer node:
```
sst_conn_tool -c -i
[PE_0]: MPI rank order: Using default aprun rank ordering.
[PE_0]: rank 0 is on nid02390
[PE_0]: cpumask set to 272 cpus on nid02390, cpumask = 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111

	ADIOS2_IP_CONFIG Possible interface lo : IPV4 127.0.0.1
	ADIOS2_IP_CONFIG Possible interface ipogif0 : IPV4 10.128.9.105
	ADIOS2_IP_CONFIG best guess hostname is "10.128.9.105"
	ADIOS2_IP_CONFIG best guess IP is "10.128.9.105"
	ADIOS2_IP_CONFIG specified port range is "ANY" (unspecified)

 	The following environment variables can impact ADIOS2_IP_CONFIG operation:
		ADIOS2_IP  		-  Publish the specified IP address for contact
		ADIOS2_HOSTNAME  	-  Publish the specified hostname for contact
		ADIOS2_USE_HOSTNAME 	-  Publish a hostname preferentially over IP address
		ADIOS2_INTERFACE  	-  Use the IP address associated with the specified network interface
		ADIOS2_PORT_RANGE  	-  Use a port within the specified range "low:high",
		                 	   or specify "any" to let the OS choose

	Sst reader at IP 10.128.9.105, listening UDP port 45867


	Attempting TCP/IP connection to writer at IP 128.55.205.20, port 40764

```

**Comment by eisenhauer** [comment]
Hi Jong!
So, the general problem here is ugly.  Many years ago, there was a "redirection" facility built into EVPath that partially addressed this, but it was far from ideal.  The basic approach was that if you knew you were on a private network (like the 10.* range), you'd maintain a control connection to a third-party "redirection server".  If someone else not in your private network wanted to connect to you, they'd instead send a message to the redirection server, which would then be relayed to you, asking you to connect to them instead.  (It also had a feature where if *both parties* were on a private network, the redirection server would act as a message relay between them.)  This worked pretty well as a proof-of-concept for TCP socket connections, but had practical problems.  First, it fails utterly for anything like RUDP, where there isn't a network-level connection abstraction built into the NAT (so you simply can't do UDP into private nets without explicit port forwarding).  Then there was the question of where to run the redirection server and how to manage its scalability.  It has to use TCP to link to its private-network clients, and since we're doing this at the EVPath level, for SST it needs a connection to every rank in every cohort on a private network.  So, you run out of file descriptors fast unless that server is itself parallelized, which is a pain.  I think I stopped maintaining this functionality long ago when IPv6 made it look like private networks were soon going to be a thing of the past. (So much for that!)

Options: 
1) I could look into reviving this EVPath functionality for TCP.  If the server wasn't parallelized, it would only work if your cohort on the private network were smaller than the FD limit (typically 1024 or 4096).  And since we'd have to use TCP between reader and writer too, your cohort size *outside* the private network would potentially be limited too, but that limit depends upon the read pattern (each reader rank needs connections to every writer rank from which it needs data, as soon as any reader or writer hits the FD limit, this fails).  You'd have to run a redirection server somewhere in non-private network and keep it running or restart it before running jobs, etc.  This is kind of a kludge, but it's pretty certain to work if your situation fits the constraints.
2) *Maybe* IPv6?  I have a RUDP implementation (newer version of ENET) that supports that.  The question is whether or not Cori and NERSC DTN and the network paths in between support that.  I think this is not impossible, and if they did, extending SST/EVPath to be IPv6 capable is more forward-looking than reviving the redirect server, and probably about the same amount of work (as I already did a good bit when poking at the new ENET).  But there's no point unless the networking can handle it.  (It's been 20 years why, why wouldn't IPv6 be everywhere, particularly on advanced systems like DOEs?)
3) There should probably be a third option, involving NATs and forwarded port ranges, but all the ones that have occurred to me so far have some fatal flaw.  And that's without considering if you could possibly get some administrator to poke holes in the firewall or modify NAT configuration.

Anyhow, let me know your thoughts here...

**Comment by jychoi-hpc** [comment]
Currently I am using only 1 writer and 1 reader. FD limit would not be a problem for now. 

Before discussing further, I have a quick question: Does SST use multiple TCP connections  (i.e., using multiple TCP ports) between two (the writer and the reader), something like one port for up-streaming and the other port for downstream? 

If it is a single TCP stream, here is my guess on the connection sequence:
1. the writer (on DTN) drops a connection file which contains his public ip. 
2. the reader reads the connection file and sends his ip address (which is private) to let the writer to connect.
3. However, the writer cannot connect to the receiver since is not visible to him. (i.e., the writer is trying to initiate TCP connection but fails)

In a "reverse" mode, maybe, we can do something like:
1. The writer saves his connection information
2. Using this information, the reader connects to the writer with TCP/IP. That's it. They can continue to use this stream (i.e., the reader initiates TCP connection)

**Comment by eisenhauer** [comment]
WRT ports and connections, generally SST will only ever open a single socket between two processes multiplexing forward and backward information exchanges over that single link, but the ports are allocated dynamically.

That you are working with one reader rank and one writer rank is a hugely simplifying condition.  I *might* be able to tweak SST so that it would work as you are thinking in "reverse" mode, because it's more of a fluke that it doesn't.

The current deal is this:  
1) the writer rank 0 saves his contact info in the file
2) the reader contacts everyone in his cohort, gathering their IP and port contact information and sends it (including his own) to the writer rank 0.
3) the writer distributes the reader rank contact information to all writer ranks, and replies to the reader rank 0 with the contact information for each of the writer ranks.
4) the reader then distributes the contact information for each writer rank to each of the readers.  At this point everyone has everyone's contact information and can make connections when necessary.  And in different situations, different sides tend to make connections.  If we're doing "peer mode" control, the writer ranks initiate those connections to their peers.  If we're not, only rank 0 writer connects to rank 0 reader right away, but then the reader ranks will initiate connections to the writer ranks as necessary to send requests for data that they need.  Now if one of those guys is behind a NAT, then most of this contact information is trash, so this will never work (without something like the redirect server).

But you're right that it should work in the very special case of one reader rank and one writer rank.  It probably doesn't because of how we identify connections to reuse and because we take a more general approach (not special-casing the rank 0 to rank 0 connection).  Generally, when someone connects to you via a socket, you don't know either what IP he's at or what port he might be listening on (if indeed he's accepting incoming connections).  EVPath uses getpeername() to identify the IP of the guy connecting, and then remembers it so that if someone tries to initiate a connection to that guy in the future, we'll just reuse the connection that we already have.  But in this case, that goes horribly wrong.  If the connecting guy is behind a NAT, the IP we get for him is the IP of the NAT router, not the (useless) address that he gave us as his contact information.  This means that when we fall into the bit of code on the writer side that sets up any connections to reader ranks that we might need, and we call CMget_conn() using the contact information he gave us, things go wrong.  If he was on a public IP, and getpeername() agreed with what he gave us, CMget_conn() on writer rank 0 would just return the existing connection, incrementing its reference count, while on other writer ranks we'd make a new connection.  But he's not on a public IP, getpeername() doesn't agree with his given contact info and CMget_conn() tries to connect to his given IP and fails, whatever rank tries it.   We *could* fix this on rank 0, storing the CMConnection on which our initial connection request came in on so that as a special case we could just add to the reference count of that connection instead of using CMget_conn().  That would probably make this work for the situation where there was one reader rank and one writer rank, and the writer had a public IP address, but the reader did not.   But if you changed any of those things, swapped which one was on the public, or added a rank to either side, you'd have to have something like the redirection server.    Making that special case work probably just involves tracking a value that is known at one point in the code (the CMConnection value in the ReaderRegisterHandler) and storing it somewhere safe until we eventually hit a later point in the code (where we're setting up writer-side connections).   However, now that I'm thinking it through, the data plane Preload functionality would probably break too.  That relies upon the data plane making its own connections, and I don't have an easy workaround for that.  (Preload is really only useful if you are either network-bound or reader-side-compute-bound, so maybe you don't care.)

Anyhow, if you still think this is useful, with those constraints and a need to disable preloading (which we'll use automatically with one reader and one writer), then let me know and I'll try to push in a fix.  Probably only a half dozen lines of code and storing a pointer somewhere for a while.

**Comment by jychoi-hpc** [comment]
Right, it is more like "connection reuse" instead of "reverse" mode. 

If it is not a huge change, I would like to try. Thank you for your input. I appreciate your update in advance.

**Comment by eisenhauer** [comment]
OK, I'll give it a shot tomorrow.  I'll let you know when there's a branch you can try.

**Comment by eisenhauer** [comment]
Hi Jong.  I'm late in giving you an update.  I merged a change into master that *may* make this possible, but I haven't been able to test it yet.  I discovered that a local testbed that would have let me test was broken, and it's always been a day away from repair/reenabling.  I don't have access to Cori at the moment, so I can't test this in the same environment you.  I'm still waiting for my local testbed, but if you want to give this a shot again with rebuilt master, please do.  I *think* it'll work at the control plane level, but since the EVPath data plane makes its own connections those would be a problem.  The regular data requests would be fine as they are initiated from the reader, but data preloading would be a problem.  It's enabled by default on 1x1 connections, so you'd need to specify the engine parameter "SpeculativePreloadMode:off" to make sure preload doesn't happen.   If you do this and it *doesn't* work, sending me output after running with environment variables "SstVerbose=1" and "CMConnectionVerbose=1" would be helpful.

**Comment by eisenhauer** [comment]
Hey Jong.  Would you please build and try the JongTest branch?  This should work for you, if on the reader side you specify the engine parameter ""SpeculativePreloadMode=off".  I tested it like this:
1) on the public IP side:  ./TestCommonWrite sst tmp "RegistrationMethod=screen"
2) on the private IP side: ./TestCommonRead sst ADIOS2Common "SpeculativePreloadMode=off,RegistrationMethod=screen"
(The screen registration method lets you just copy and paste the contact info from one window to another.)

This is *not* the right fix yet because I'm still thinking about how best to spec it.  The current implementation anticipates the possibility of using a different network transport (e.g. enet or sockets) for the EVPath data plane, vs what is used for the control plane, so the data plane *always* gets its own connection, even when just responding to a request.  Generally I think that's the right approach, but it needs tweaking here and I've not decided quite how is best.  This test eliminates that feature and is just so that you can try things to see if it's useful.

**Comment by jychoi-hpc** [comment]
Greg, thank you for the update. I am building now and let you know any result soon.

**Comment by jychoi-hpc** [comment]
Greg, it works now. Thank you for the quick fix. I will do a few more checks and tests and let you know if there is any news.

**Comment by jychoi-hpc** [comment]
@eisenhauer Is this merged to the master branch? I need to use master branch as there is a fix I need to use.

**Comment by eisenhauer** [comment]
Not yet, but as a first step, let me rebase on current master.  I just need to sort out how best to enable this when we want it, leaving the flexibility/robustness to create our own connections when we can.
