### ISSUE TITLE
bindings/Python: Cannot initialize serial ADIOS if MPI is enabled

### ISSUE THREAD

**Issue by dmitry-ganyushin** [ornladios/ADIOS2#2233]
Hello,

It looks like adios initialization in python  does not work with a parameter.
From examples/hello/bpWriter/helloBPWriter_nompi.py

adios = adios2.ADIOS(adios2.DebugON)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
mpi4py/MPI/CAPI.pxi in mpi4py.MPI.PyMPIComm_Get()

TypeError: Cannot convert bool to mpi4py.MPI.Comm

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-6-f6f117954d62> in <module>()
----> 1 adios = adios2.ADIOS(adios2.DebugON)

SystemError: <built-in method __init__ of PyCapsule object at 0x7f0cfa9bfcc0> returned a result with an error set

**Comment by godoywf** [comment]
@dmitry-ganyushin  that's the signature for the non-mpi build.  I'd check with @bradking as he reworked the entire MPI/non-MPI toolchain. Hope it helps.

**Comment by chuckatkins** [comment]
@dmitry-ganyushin the debug parameters have been deprecated as they are no longer used internally.  The intent was to keep backwards compatible interfaces that silently dropped the argument but it looks like we may have missed that for the python bindings.  So it looks like we need to 1) add the backwards compatible interface and 2) fix the python examples to not use the deprecated function signature.

**Comment by bradking** [comment]
The `examples/hello/bpWriter/helloBPWriter_nompi.py` example is named `_nompi` because it is meant for use in the case that ADIOS2 was built without MPI enabled.  If ADIOS2 is built with `ADIOS2_USE_MPI` set to `OFF` then the example works:

```python
adios = adios2.ADIOS(adios2.DebugON)
```

If ADIOS2 is built with `ADIOS2_USE_MPI` set to `ON` then the `examples/hello/bpWriter/helloBPWriter.py` example works instead:

```python
comm = MPI.COMM_WORLD
adios = adios2.ADIOS(comm, adios2.DebugON)
```

Each of those  bpWriter examples says in comments at the top "only works with MPI version" or "only works with non MPI version", though it looks like those are backwards.

That said, I've made a bunch of changes recently to make serial programs work with a MPI-enabled ADIOS2.  This issue demonstrates that the Python bindings still haven't been fixed for that.
