### ISSUE TITLE
Fortran documentation out-of -date

### ISSUE THREAD

**Issue by hr87** [ornladios/ADIOS2#2474]
**Describe the bug**
The Fortran documentation is lacking descriptions for several routines. The one I found missing is `adios2_attribute_data`. Furthermore, it seems like the documentation for `adios2_set_steps_selection` is actually for the wrong method. Additionally, the description for the latter is not clear in the C++ section either.

**To Reproduce**
 1) Go to the documentation
 2) Look for adios2_attribute_data

**Expected behavior**
Find a clear description of method

**Comment by williamfgc** [comment]
@hr87 thanks for pointing this out. Yes, the Fortran docs are a bit of a pain to maintain since they are not automatically handled by readthedocs + breathe + doxygen (same with tests, there is currently no testing framework, but just assert style checks).  It's the hassle of mixing Fortran and modern infrastructure. Fortran bindings are essentially (almost) replicating the C bindings (those are automatically handled), check the docs for [adios2_set_steps_selection](https://adios2.readthedocs.io/en/latest/api_full/api_full.html#_CPPv425adios2_set_step_selectionP15adios2_variableK6size_tK6size_t). Also, since adios2 relies on its community members, feel free to do a PR at anytime since all of the documentation source code resides under `docs` in particular [Fortran full APIs](https://github.com/ornladios/ADIOS2/blob/master/docs/user_guide/source/api_full/fortran.rst).

**Comment by dmitry-ganyushin** [comment]
Documentation updated with PR #2559
