### ISSUE TITLE
TestBPWriteReadJson is not stable when running in MPI

### ISSUE THREAD

**Issue by HaochengLIU** [ornladios/ADIOS2#254]
BPWriteReadJson test would fail from time to time with a Json parser error. For now it's disabled to make dashboard green.
CDash reference [link](https://open.cdash.org/testDetails.php?test=578989776&build=5042280).

**Comment by williamfgc** [comment]
@HaochengLIU   the error seems to be due to our third party json reader not being able to parse the profiling.json file. I can't reproduce the issue on any of my systems, can you make sure that the created file is accessible? A separate issue, is that the number of bytes is harcoded, but that should be platform independent and it's not what the error message is telling us. Let me know.

**Comment by HaochengLIU** [comment]
Hi William, thanks for looking into this and I can not reproduce this bug on my laptop also... Let's record this issue on github for now.

**Comment by williamfgc** [comment]
@HaochengLIU like @chuckatkins said, it's a Heisenbug....still, this will be changed in the long-term. I needed some kind of first order profiling info for the tests on Titan. Thanks!
