### ISSUE TITLE
SST and MPI engines not delivering data in python

### ISSUE THREAD

**Issue by hughed2** [ornladios/ADIOS2#2829]
**Describe the bug**
When I use python reader/writer scripts with SST or MPI based engine, the read data is always empty regardless of what was written. File based engines work with otherwise identical scripts, however. I'm not sure whether this is a bug, or if I'm using it improperly--although if I'm doing something wrong, I'd expect file based engines to fail as well. Note that I've only tried this in python.

**To Reproduce**
cat testWrite.py
```
import adios2
from mpi4py import MPI

import numpy as np

print("Trying to open a write instance")
with adios2.open("foo", "w", MPI.COMM_SELF, engine_type="sst") as foow:

    print("Trying to write")
    foow.write("bar", np.array([1,5,10]), end_step=True)

    print("Finished with write")
```

cat testRead.py
```
import adios2
from mpi4py import MPI

import time
print("Sleeping before read")
time.sleep(5)

print("Trying to open a read instance")
with adios2.open("foo", "r", MPI.COMM_SELF, engine_type="sst") as foor:

    print("Trying to read")
    bar = foor.read("bar")
    print(bar)
```

mpirun --np 1 python testRead.py : --np 1 python testWrite.py
```
Sleeping before read
Trying to open a write instance
Trying to write
Trying to open a read instance
Trying to read
[]
Finished with write
```

Instead of displaying an empty list, it should be displaying the [1,5,10] that was passed in by the writer. I get the same results for "insitumpi" engine (I've also tried a few based on SST, like insituanalysis, which unsurprisingly also fails). If I try something like "bp4" or "filestream", on the other hand, it correctly displays the [1,5,10].

**Desktop (please complete the following information):**
Using RHEL 7.9, OpenMPI 2.1.3

Thanks in advance for any help!

**Comment by williamfgc** [comment]
@hughed2 streaming engines need to advance steps in order to work, unlike file based engines they can only "view" one step at a time. In the Python high-level API this is a `for step in foor` loop. See [the example](https://adios2.readthedocs.io/en/latest/api_high/api_high.html#python-write-example) in the docs. Also, the [paper](https://www.sciencedirect.com/science/article/pii/S2352711019302560) is a good starting point as adios2 API is designed with streaming in mind, the non-streaming API (without advancing steps) is just for convenience for random-access file based engines. Hope it helps.

**Comment by hughed2** [comment]
Great, thank you. I've got it working now. I hadn't realized that the interface for file vs streaming based engines would be different in that regard.
