### ISSUE TITLE
Passing inline data between languages (Fortran and C++)

### ISSUE THREAD

**Issue by aradi** [ornladios/ADIOS2#2908]
I wonder, whether it is possible with the current state of ADIOS2 to pass data via the `Inline` engine between Fortran and C/C++. 

**Why is this feature important?**
It would enable passing of complex data in mixed language scenarios, such as a C++ software package with an embedded Fortran simulation library or vice versa.

- The simulation library returns the quantities it had calculated in such a data structure. Caller investigates the data and reads out the quantities (energy, forces, ...) it is interested it. This would help us to avoid, that the library has to provide an API with individual calls for each quantity.

- Fine-grained initialization of the simulation library. Some codes (e.g. [DFTB+](https://github.com/dftbplus/dftbplus), which I am a main developer of) already allow for an [initialization with a data tree](https://github.com/dftbplus/dftbplus/blob/7455efc2eae9e0cc2673aec0b4aa4735c5a5962c/test/src/dftbp/api/mm/testers/test_treeinit.f90#L62), which contains the same (hierarchical) data as a normal input file would usually contain. For DFTB+, this currently works only when initialized from Fortran, it would be nice to be able to cross the language barrier.

**What is the potential impact of this feature in the community?**
Seamless passing of complex data in mixed-lanuage projects.

**Describe the solution you'd like and potential required effort**
Being able to assemble a hierarchical data structure in one language and read it out in an other. I have no clue, how complicated it would be to have it in ADIOS2 (or whether it can be done already...)

**Describe alternatives you've considered and potential required effort**
I could probably take Conduit, as it seems to have it [already implemented](https://github.com/LLNL/conduit/blob/develop/src/examples/cpp_fort_and_py/conduit_fort_and_py_ex.F90). I could also implement a simple and lightweight solution myself, but if it could be done via ADIOS2, I'd like to give it a try.

**Comment by williamfgc** [comment]
@aradi you're welcome. I agree on the Fortran ISO C bindings, we hold on to that since we support several frameworks written in Fortran 90. @eisenhauer and @pnorbert typed faster, I wanted to ask about the scope of your data (if the reader outlives your writer, go with default BP4 file engine, if it's during the process, both BP4 and SST will need to sync between readers and writers). Still SST and BP4 (file) are buffer-based (serialize first and send), my understanding is that `inline` is more about passing pointers (address) around seamlessly, which I understood that's what you're looking for. Still the multi-language aspect is probably not covered today with `inline`. 

Regardless of engine of choice, I would write the workflow using streaming capabilities (engine's `BeginStep` and `EndStep`, SST doesn't work without those) and switch between engines depending on your scenario (the seamlessly aspect that @pnorbert mentioned).

If it helps, there is a test (file only) for interoperability of a [C++ reader](https://github.com/ornladios/ADIOS2/blob/master/testing/adios2/bindings/fortran/TestF2C_BPReadFBlocks.cpp) for [Fortran writers](https://github.com/ornladios/ADIOS2/blob/master/testing/adios2/bindings/fortran/TestBPWriteReadHeatMap2D.F90).
Like @pnorbert said, flipping fast/slow indexing is something to be careful about. I always make that mistake when coding on the same day with Fortran and C++.

**Comment by aradi** [comment]
Actually I may need communication in both ways: "writing" data in C, entering the Fortran routine (in the same process), reading out the data in Fortran, process it, writing an "answer" in Fortran (maybe with a separate writer), returning from the Fortran routine to the C-caller, reading out the data and process it (and so on, and so on). This would enable me to exchange structured "messages" between parts of a program, which are written in different languages. I'll try to set up a small example using the BP4 writer/reader first.

@williamfgc As for the Fortran interface. Using the ISO-C bindings won't affect external projects at all, as it would not necessary change your Fortran interface. You just would make sure, that whenever you call a C-function from within your current Fortran wrappers, argument types etc. would be checked for. Also, you would make sure, that it would work with different compilers, independent whether they tend to append `_` to names. (Oh, and as for `real(8)`: is not standard Fortran. There are Fortran compilers out there, which won't understand this. Using `real(wp)` with `wp` being `real64` on the other hand would work compiler independent. And again, it would only improve the robustness on your side, it won't affect what external projects using ADIOS2 see...) I am really not criticizing, I am just always sad if modern and cool projects are using ugly 30 years old hacks when dealing with Fortran. :wink:
