### ISSUE TITLE
macOS: Universal2 build fails

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#3116]
Hi,

We ship openPMD-api as binary wheels for python users containing ADIOS2  for postprocessing tasks.

With ARM being strong with the Apple M1 processors, we want to build universal2 wheels that contain both x86_64 and arm64 code. We produce them on macOS 11.0 x86_64 GitHub actions runners.

Multi-arch builds for macOS are very easy with CMake, we just need to set:
```bash
export CMAKE_OSX_ARCHITECTURES="arm64;x86_64"
```

Unfortunately, dill breaks the build for 2.7.1:
```
Users/runner/work/openPMD-api/openPMD-api/src/ADIOS2-2.7.1/thirdparty/dill/dill/x86_64.c:2595:20: error: unrecognized instruction mnemonic
              asm volatile ("clflush (%0)" : /* */ : "r" (ptr));
                            ^
  <inline asm>:1:2: note: instantiated into assembly here
          clflush (x8)
          ^
```

X-ref: https://github.com/openPMD/openPMD-api/pull/1233

Refs.: https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

**Comment by ax3l** [comment]
@eisenhauer I believe that's a dill issue and this something in your reign?

cc @chuckatkins

**Comment by eisenhauer** [comment]
This bit is probably me, but I need to look into this universal build thing.  Dill does dynamic code generation, and x86_64.c contains a whole lot more than just this ASM statement that is specific to the architecture we're executing on (as do the arm*.c files, which we'd be using on ARM archs).  Making all this do the right thing in some "universal" way may be non-trivial...

**Comment by ax3l** [comment]
Thank you @eisenhauer, I'll try it (on 2.7.1)! :)

**Comment by eisenhauer** [comment]
Hmm.   The patch is big, because of lots of CI things that were put into Dill.  BUT, the only important bits are the #ifdef ___x86_64__ in x86_64.c and x86_64_rt.c that protect the ASM statements.   (Honestly, this is sufficient to get dill to compile.  There's more CMake stuff that would be required to make it work on ARM, because we're not currently building the ARM bits in universal, just the x86 bits.  But ADIOS isn't currently using those machine-specific bits, so it shouldn't doesn't matter.)   So if you just try protecting the ASM with that ifdef, you should be fine.

**Comment by chuckatkins** [comment]
@ax3l the just-cut 2.8.0 release should have upstream dill.  I'll add a universal binary into our CI build to ensure it keeps working
