### ISSUE TITLE
adios remove IO: wrong return value

### ISSUE THREAD

**Issue by dmitry-ganyushin** [ornladios/ADIOS2#3172]
The C function ```adios2_remove_io``` returns false after an attempt to remove an IO object.

The C++ implementation needs to be corrected.
From ADIOS.cpp
```
bool ADIOS::RemoveIO(const std::string name)
{
    if (m_IOs.erase(name) == 1)
    {
        return true;
    }

    return false;
}
```
In C++11 the ```std::map erase(key)``` method returns an iterator to another object in map and it cannot be compared with 1.
Documentation should be corrected too.

**Comment by eisenhauer** [comment]
Are you sure?  std::map erase with a key parameter (as opposed to one or two iterator parameters) returns size_t, the number of elements erased.   This didn't change in C++11 (though the profile of erase with iterator parameters did)...

**Comment by eisenhauer** [comment]
I don't think there's a right or wrong answer in the question of how to handle errors, either by returning an error condition the user is expected to check or to throw an exception.   We should probably try to be kind of consistent though (and of course throwing an exception makes the non-C++ apis more complex because that exception has to be caught in C++ and turned into an error return).
