### ISSUE TITLE
Cannot build ADIOS2 with HDF5

### ISSUE THREAD

**Issue by eschnett** [ornladios/ADIOS2#3203]
I am building ADIOS2 2.8.0 with HDF5 1.12.1. I am building via Spack as `adios2 ~fortran +hdf5 ~python`. This fails with the error
```
  >> 1203    "/tmp/eschnetter/spack-stage/spack-stage-adios2-2.8.0-gnonxlrnqyn6uxtxbidqfh73slcwdrgs/spack-src/source/adios2/toolkit
             /interop/hdf5/HDF5Common.cpp", line 1632: error: too many arguments in function call
     1204          herr_t ret = H5Oget_info(m_FileId, &oinfo, H5O_INFO_ALL);
```

I assume that the problem is that ADIOS2 is expecting a different HDF5 API.

**Comment by ax3l** [comment]
ping @guj @pnorbert

**Comment by ax3l** [comment]
This is fixed in `master`:
https://github.com/ornladios/ADIOS2/blob/00a7dca910dd6941995634e236f3fed47f3f7d28/source/adios2/toolkit/interop/hdf5/HDF5Common.cpp#L1631-L1639 aka 55433ecc90ad8c999aa4675b888d4c3ee5700dea / #3156

It's already marked for the 2.8.1 release (also part of `release_28` branch).

**Comment by vicentebolea** [comment]
Should this be closed?
