### ISSUE TITLE
Memory leaks in BP5Writer

### ISSUE THREAD

**Issue by dqwu** [ornladios/ADIOS2#3381]
This issue is reproducible with latest ADIOS2 2.8.3 and a simple C example of SCORPIO.

Steps to reproduce on a Linux workstation with GCC compiler and its LeakSanitizer:
```
git clone https://github.com/E3SM-Project/scorpio.git
cd scorpio

mkdir build
cd build

CFLAGS="-fsanitize=leak -fno-omit-frame-pointer -g" \
ADIOS2_DIR=/path/to/adios2/installation \
CC=mpicc CXX=mpicxx FC=mpifort cmake -Wno-dev \
-DWITH_ADIOS2=ON \
-DWITH_NETCDF=OFF \
-DPnetCDF_PATH=/path/to/pnetcdf/installation \
-DPIO_USE_MALLOC=ON \
-DPIO_ENABLE_EXAMPLES=ON \
..

make

cd examples/c
mpiexec -n 2 ./example1
```
Example output on a Linux workstation of ANL:
```
=================================================================
==1286003==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7ff9249441d4 in __interceptor_malloc /nfs/gce/software/tmp/svcbuilder/spack-stage-gcc-11.1.0-qsjmpcgt7go2ourefdh2i5z2g5u7bxmk/spack-src/libsanitizer/lsan/lsan_interceptors.cpp:56
    #1 0x829832 in adios2::core::engine::BP5Writer::MarshalAttributes() ADIOS2-2.8.3/source/adios2/engine/bp5/BP5Writer.cpp:464
    #2 0x83c6ed in adios2::format::BP5Serializer::AddSimpleField(_FMField**, int*, char const*, char const*, int) ADIOS2-2.8.3/source/adios2/toolkit/format/bp5/BP5Serializer.cpp:159
```
Valgrind also reports similar memory leaks:
```
==1280300== 8 bytes in 1 blocks are definitely lost in loss record 1 of 3
==1280300==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1280300==    by 0x829832: adios2::core::engine::BP5Writer::MarshalAttributes() (in scorpio/build/examples/c/example1)
==1280300==    by 0x82E830: adios2::core::engine::BP5Writer::EndStep() (in scorpio/build/examples/c/example1)
==1280300==    by 0x4E8907: adios2_end_step (in scorpio/build/examples/c/example1)
==1280300==    by 0x4518E8: end_adios2_step (in scorpio/build/examples/c/example1)
==1280300==    by 0x44F043: PIOc_closefile (in scorpio/build/examples/c/example1)
==1280300==    by 0x44D929: main (in scorpio/build/examples/c/example1)
```

**Comment by eisenhauer** [comment]
Thank you for the report.  This leak is in the handling of array attributes in BP5 serialization.  That handling has been completely rewritten for the next release (2.9) in order to improve performance and I believe that this bug was fixed by that rewrite.  If you get a chance to try this again, with ADIOS master, please let us now the result.  (The 2.9 release is pending, but we don’t have a date yet…)

From: dqwu ***@***.***>
Date: Friday, November 11, 2022 at 3:24 PM
To: ornladios/ADIOS2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ornladios/ADIOS2] Memory leaks in BP5Writer (Issue #3381)

This issue is reproducible with latest ADIOS2 2.8.3 and a simple C example of SCORPIO.

Steps to reproduce on a Linux workstation with GCC compiler and its LeakSanitizer:

git clone https://github.com/E3SM-Project/scorpio.git

cd scorpio



mkdir build

cd build



CFLAGS="-fsanitize=leak -fno-omit-frame-pointer -g" \

ADIOS2_DIR=/path/to/adios2/installation \

CC=mpicc CXX=mpicxx FC=mpifort cmake -Wno-dev \

-DWITH_ADIOS2=ON \

-DWITH_NETCDF=OFF \

-DPnetCDF_PATH=/path/to/pnetcdf/installation \

-DPIO_USE_MALLOC=ON \

-DPIO_ENABLE_EXAMPLES=ON \

..



make



cd examples/c

mpiexec -n 2 ./example1

Example output on a Linux workstation of ANL:

=================================================================

==1286003==ERROR: LeakSanitizer: detected memory leaks



Direct leak of 8 byte(s) in 1 object(s) allocated from:

    #0 0x7ff9249441d4 in __interceptor_malloc /nfs/gce/software/tmp/svcbuilder/spack-stage-gcc-11.1.0-qsjmpcgt7go2ourefdh2i5z2g5u7bxmk/spack-src/libsanitizer/lsan/lsan_interceptors.cpp:56

    #1 0x829832 in adios2::core::engine::BP5Writer::MarshalAttributes() ADIOS2-2.8.3/source/adios2/engine/bp5/BP5Writer.cpp:464

    #2 0x83c6ed in adios2::format::BP5Serializer::AddSimpleField(_FMField**, int*, char const*, char const*, int) ADIOS2-2.8.3/source/adios2/toolkit/format/bp5/BP5Serializer.cpp:159

Valgrind also reports similar memory leaks:

==1280300== 8 bytes in 1 blocks are definitely lost in loss record 1 of 3

==1280300==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)

==1280300==    by 0x829832: adios2::core::engine::BP5Writer::MarshalAttributes() (in scorpio/build/examples/c/example1)

==1280300==    by 0x82E830: adios2::core::engine::BP5Writer::EndStep() (in scorpio/build/examples/c/example1)

==1280300==    by 0x4E8907: adios2_end_step (in scorpio/build/examples/c/example1)

==1280300==    by 0x4518E8: end_adios2_step (in scorpio/build/examples/c/example1)

==1280300==    by 0x44F043: PIOc_closefile (in scorpio/build/examples/c/example1)

==1280300==    by 0x44D929: main (in scorpio/build/examples/c/example1)

**Comment by dqwu** [comment]
@eisenhauer It turns out that I cannot reproduce the memory leaks with latest ADIOS2 master branch. I think this issue can be closed, thanks.

**Comment by eisenhauer** [comment]
Great, thanks for testing!
