### ISSUE TITLE
ERROR: One or more process (first noticed rank 0) terminated with signal 9.

### ISSUE THREAD

**Issue by ZhenluQin** [ornladios/ADIOS2#3429]
When I followed adiosvm (https://github.com/norbert/adiosvm), used ADIOS2 (2.8.1) and Gray-Scoot for testing the performance. When L=2048, the program crashed before the first step. It showed the error message **'ERROR: One or more process (first noticed rank 0) terminated with signal 9'.** But L=1024 can work well.  I have tested BP4/BP5, and the same errors happened. I wonder if this is because the data I set is too large to meet the required resources.

 Specifically, I positioned it to terminate before writer.EndStep();.  The lengths of var_u and var_v are correct, because I have adjusted the length from int to size_t, and the result of print is 8615125000=(2048+2)*(2048+2)*(2048+2).
        writer.BeginStep();
        writer.Put<int>(var_step, &step);
        writer.Put<double>(var_u, u.data());
        writer.Put<double>(var_v, v.data());
        writer.EndStep();

I run it on the Summit with jsrun. (jsrun -n1 -a1 -c1 -g0 build/gray-scott simulation/2048/settings-files.json)
Parts of adios2 config:
io name="SimulationOutput"
   engine type="BP5"
   parameter key="RendezvousReaderCount" value="0"
   parameter key="QueueLimit" value="1"
   parameter key="QueueFullPolicy" value="Discard"
   parameter key="OpenTimeoutSecs" value="10.0"
   parameter key="MaxStreamsPerApp" value="2"

Simulation descriptions:
Simulation writes data using engine type:              BP5
grid:             2048x2048x2048
steps:            10
plotgap:          1
F:                0.01
k:                0.05
dt:               2
Du:               0.3
Dv:               0.3
noise:            1e-07
output:           different_bp/2048/gs_no.bp
adios_config:     adios2.xml
process layout:   1x1x1
local grid size:  2048x2048x2048

Thank you very much,

**Comment by eisenhauer** [comment]
It's hard to be certain where you're having problems, in part because you've presumably adjusted some things.  As you observe, gray-scott wasn't really written with such large sizes in mind and it uses 'int' as an index type in a number of places.  But when I did a quick check in a limited-resource environment (my laptop), I adjusted the appropriate values in gray-scott.cpp from int to size_t.  With L=2048 in GrayScott::init_field(), it to a very long time in the u.resize() line (because of having to init so much data) and then failed with a signal 9 trying to do v.resize() on the next line.  If I were guessing, I'd guess that yes, you are exhausting available resources, perhaps before you get to the point of invoking ADIOS.  If you're just running on one node you could actually try running in the debugger in an interactive job to find out for sure.

**Comment by ZhenluQin** [comment]
OK. I think you are right. Thank you, and I will close this.
