### ISSUE TITLE
GCC build on Perlmutter failing at end of install in something with libperfstubs version labeling

### ISSUE THREAD

**Issue by suchyta1** [ornladios/ADIOS2#3645]
When I'm trying to build on Perlumtter with GCC, the build process gets the end of the install command to make, where it can't find `libperfstubs.so.2.9.0`, and when I do an `ls`, it's just named `libperfstubs.so.2.9` without the `.0`. I've attached the full log and my build environment in the attached log. Here I used GGC 11.2.0, but I've seen the same trying to use other versions.
[build.log](https://github.com/ornladios/ADIOS2/files/11600070/build.log)

**Comment by suchyta1** [comment]
Actually the links look like: 

> lrwxrwxrwx 1 esuchyta m499   28 May 30 05:39 libadios2_perfstubs.so.2.9 -> libadios2_perfstubs.so.2.9.0
> lrwxrwxrwx 1 esuchyta m499   26 May 30 05:39 libadios2_perfstubs.so -> libadios2_perfstubs.so.2.9

So I guess it is ultimately that `libadios2_perfstubs.so.2.9.0` isn't there.

**Comment by eisenhauer** [comment]
Perhaps a CMake thing @vicentebolea ?  @suchyta1, are those links you give from the build or from the install lib directory?

**Comment by suchyta1** [comment]
Those links are from listing `lib64` of the build directory.

**Comment by caitlinross** [comment]
I was able to reproduce the problem on my linux system and I think I see what's going on. It's because you set the install directory to be the same as your build directory. During the install step, there's a cmake file (`adios-build/thirdparty/perfstubs/perfstubs/cmake_install.cmake`) that checks the rpath of `libadios2_perfstubs.so.2.9.0` (and this would actually happen for any of the third party libs, perfstubs just happens to be first). Apparently `file(RPATH_CHECK ...)` will delete the file if rpath is not what it's supposed to be.

You can fix it by setting a directory for your install to be different from the build directory.

**Comment by suchyta1** [comment]
Thanks, yes that does resolve it. It was an oversight on my part that I hadn't set the intended install path.
