### ISSUE TITLE
Some Stagging BP5 test failing in Windows

### ISSUE THREAD

**Issue by vicentebolea** [ornladios/ADIOS2#3723]
The following unit tests:
```
Staging.1x1DefSync.BP5
Staging.1x1DataWrite.BP5
```
In windows builds as shown here: https://open.cdash.org/viewTest.php?onlyfailed&buildid=8871942

Currently the are flaky in multiple PRs, (not master yet), we need to fix them.

**Comment by eisenhauer** [comment]
These are failing because they are timing out, not because of an actual bug.  It looks like the timeout is 2 minutes, but a commit to master a month ago (e08dba0420a59ee6403486360dd54a6c9b5e8dd7) changed that to 3 minutes to address this.  And BP5 is only on Windows in Master, so I'm not sure how this is happening...  Can you check that this build has this commit:  https://github.com/ornladios/ADIOS2/commit/e08dba0420a59ee6403486360dd54a6c9b5e8dd7

**Comment by vicentebolea** [comment]
Fixed in #3726
