### ISSUE TITLE
Location of <adios2_path>/include/Info.h

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#3757]
Thank you for the new functionality to check variants of the ADIOS2 installation in 2.9.1!

```
adios2_available_engines
adios2_available_features
adios2_available_operators 
```

We noticed the file `Info.h` is prone to collisions due to its generic name:
```
ls <prefix>/include/
adios2/
adios2_c.h
adios2.h
Info.h
```
Example: imagine `<prefix>` being `/usr` for a Linux distribution.

Could this header be renamed to `adios2_info.h` or be moved into the `adios2/` subdirectory?

**Comment by ax3l** [comment]
cc @vicentebolea @pnorbert @franzpoeschel @guj I opened this as discussed today

**Comment by ax3l** [comment]
Another potential issue I see:
The
```
extern const int adios2_version_major;
extern const int adios2_version_minor;
extern const int adios2_version_patch;
extern const char adios2_version_str[];
```

are globals. Could this potentially cause issues if users down the road need to combine multiple ADIOS2 libraries, potentially of different versions, linked with symbol hiding/wrapping? A simple function to queries these ints might less complex?

**Comment by vicentebolea** [comment]
@ax3l thanks for pointing this out. This is indeed something to fix

>  Could this potentially cause issues if users down the road need to combine multiple ADIOS2 libraries, potentially of different versions, linked with symbol hiding/wrapping?

If an user wants to combine multiple ADIOS2 libraries, most of the symbols will clash (due to duplicated symbols while linking when). We do no hide symbols in ADIOS2 so far  (only in some components we do). if an user wants to use that in their build these symbols will be not different then any other symbols in the API.
