### ISSUE TITLE
Engine.BetweenStepPairs() always false

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#3802]
This function is not tested in CI.
I am trying to use it in an applications and it seems to be always false. 
core.Engine has a protected field
```
    /** true: Currently executing after BeginStep and before EndStep
     */
    bool m_BetweenStepPairs = false;
```

BP5Writer has a private field
```
    bool m_BetweenStepPairs = false;
```

Which one is returned in the public API? 

note: anyway, I can't use this flag as it is only implemented by BP5 and not by BP4.

**Comment by eisenhauer** [comment]
This is a leftover from extending the BP5 semantics to other engines.  The flag (and maybe the function?) got added to the engine class, but not removed from the BP5 subclass, and it wasn't noticed because it was only used inside each subclass.  As a result, BP5 used it's version, while everyone else used the engine-level version.  The engine function should have been working for non-BP5 engines.  PR #3803 should fix it for BP5 by removing that leftover member.

(Note:  it should be implemented in BP4 because the member variable (not the method) is used to throw exceptions if you screw up begin/end step.)
