### ISSUE TITLE
Add pickle support with pybind11

### ISSUE THREAD

**Issue by robcaulk** [ornladios/ADIOS2#3808]
Hey Adios team,

Is there any chance the Adios team might be willing to add Python pickling support to the adios2 python bindings? 

It should be straight forward: 

https://pybind11.readthedocs.io/en/stable/advanced/classes.html?highlight=pickle#pickling-support

We need this support to enable our fault tolerance mechanisms in [Melissa](https://gitlab.inria.fr/melissa/melissa). We open the engines on our readers, we hold those engine objects in a dictionary so that we can scan/get data periodically. If the reader process goes down, we would like to have the adios2 python engine objects pickled to disk so that we can unpickle and continue reading from the adios2 writers.

Let me know if you see an alternative solutions to pickling.

Thanks for the consideration,

Robert

**Comment by eisenhauer** [comment]
My first (and possibly uninformed) reaction is that this is likely far from straightforward.  The state of the reader-side engines is in C++ (and there's quite a lot of it) as well as some in the OS WRT open FDs, file pointers, etc.  That's just if you're reading from files, but I think you're using SST, yes?  In SST the writer side will detect a failed reader, shut down the outbound socket connections and change its internal state accordingly.  Re-initiating the connection between writer and reader would involve a lot more than just unpickling the reader state and letting it run from where it stopped.  

Not saying that this is impossible, but I don't see a way in which it would not be a major project, at least if approached from a pickling-an-engine point of view.   Having said that, it might be more approachable if done outside of ADIOS.  That is, a Melissa reader might keep track of what writer it was connected to, and reconnect upon unpickling.   I don't know enough to know if that would be sufficient or not, but it would work better in SST than with the other engines because SST in particular was designed for readers that come and go.

**Comment by robcaulk** [comment]
Thanks Greg,

Indeed, if SST is designed for readers coming and going, then it is likely more easily done on our side.

So if I understand correctly, a reader can disconnect from a writer, then another one can setup a new SST engine and  call `Open()` on that same writer? All while the writer is simply beginning and ending steps in a loop? In other words, it’s just a matter of calling the `Open()` again whenever a writer dies?

thanks for your consultation,

rob

**Comment by eisenhauer** [comment]
SST is largely designed around working scenario where the writers are large scientific simulations (in the DoE space), and that their output may be consumed by one or more analysis/visualization tools that might come and go.  So the writer is mostly a simple data producer and there are various semantics and options for what happens to the data it produces when there are no readers, when there are many, when the readers don't consume it quickly enough, etc.  Additionally, both sides detect the other's failure.  For the reader, the writer failure shows up at the application level as an end-of-stream on BeginStep, though depending upon the timing of the writers failure you could get an exception when trying to read data.  However, on the writer side, reader failure is handled internally, cleaning up and freeing resources, but not notifying at the application level (don't want to disturb that large simulation).  So there's a bit of asymmetry here that might be trouble depending upon your usage scenario.  Also, the writer is the guy who's putting out his contact info (in the named file that the reader Open()s).   If a reader fails, a substitute could immediately restart, get the writer's contact info from the same file and you're up and running.  The writer would handle the departure and reconnection internally to SST.  But if a writer fails, the reader application would have to catch that failure (EndOfStream or exception), and do a manual re-open to the new writer, potentially having to wait a bit for the new writer to replace the contents of the old file with his new contact information.

**Comment by williamfgc** [comment]
@robcaulk adios2 is used for checkpoint-restart (save a state to disk every so often). The data and trade-off would depend on your application. Hope it helps.

**Comment by robcaulk** [comment]
Thanks @eisenhauer , that solved my question. I really appreciate your thoughtful help on this matter. 

@williamfgc thanks! Actually, we are trying to checkpoint the reader itself, not the writer. In fact, we have constructed a pretty non-traditional adios configuration where we have multiple independent readers, each scanning multiple independent writers. We use Adios2 to get better data model handling and improved performance (infiniband).
