### ISSUE TITLE
C API binding fails when reading

### ISSUE THREAD

**Issue by manauref** [ornladios/ADIOS2#3843]
**Bug description**
The C version of helloBPReader.cpp is not behaving as expected. There may be issues with how `adios2_inquire_variable` and `adios2_available_variables` are behaving, and therefore I have not been able to read BP files with the C API.

**To reproduce**
First compile and run hellowBPWriter.c (attached) to generate the bp file we will later try to read:
```
mpicc helloBPWriter.c -o helloBPWriter.x -Wl,-rpath,<path_to_adios2>/lib <path_to_adios2>/adios2-2.9.1/lib/libadios2_c_mpi.2.9.1.dylib <path_to_adios2>/lib/libadios2_c.2.9.1.dylib -DADIOS2_USE_MPI -isystem <path_to_adios2>/include
mpirun -np 1 ./hellowBPWriter.x
```
then compile and run helloBPReader.c (attached) with
```
mpicc helloBPReader.c -o helloBPReader.x -Wl,-rpath,<path_to_adios2>/lib <path_to_adios2>/adios2-2.9.1/lib/libadios2_c_mpi.2.9.1.dylib <path_to_adios2>/lib/libadios2_c.2.9.1.dylib -DADIOS2_USE_MPI -isystem <path_to_adios2>/include
mpirun -np 1 ./helloBPReader.x
```

**Expected behavior**
Execution of helloBPReader.x should print out
```
myFloats:
0 1 2 3 4 5 6 7 8 9
```
instead it prints nothing or `null`, because both `adios2_inquire_variable` and `adios2_available_variables` are not detecting the variable `bpFloats` variable in the bp file.

**Desktop**
- MacOS Ventura 13.4
- Built adios2-2.9.1 with cmake, here's the full cmake config command
```
CC=$MPICC CXX=$MPICXX cmake ../ -DCMAKE_C_FLAGS="-g -O3 -fPIC" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PREFIX -DBUILD_TESTING=OFF -DADIOS2_BUILD_EXAMPLES=OFF -DADIOS2_USE_Fortran=OFF -DADIOS2_USE_HDF5=OFF -DADIOS2_USE_Python=ON -DPYTHON_LIBRARY=$PYTHON_DIR/lib/python3.11/ -DPYTHON_INCLUDE_DIR=$PYTHON_DIR/include/python3.11/ -DPYTHON_EXECUTABLE=$PYTHON_DIR/bin/python -DPython_NumPy_INCLUDE_DIR=$PYTHON_DIR/lib/python3.11/site-packages/numpy/ -DPythonModule_mpi4py_PATH=$PYTHON_DIR/lib/python3.11/site-packages/mpi4py/
```

**Additional context**
I actually wrapped adios2 in Lua, which led me to this problem and then I reproduced it in pure C.

[helloBP.zip](https://github.com/ornladios/ADIOS2/files/12874714/helloBP.zip)

**Comment by eisenhauer** [comment]
Unfortunately, this is a known behavior change that was telegraphed in the release notes for ADIOS 2.8 and 2.9, but you kind of had to read both to understand the implications.  Release 2.8 introduced augmented Mode::Read with Mode::ReadRandomAccess for the new BP5 file engine.  Prior BP engines mixed two different ways of accessing data, 1) stepping through it timestep by timestep and 2) allowing direct access to any step of any variable.  This mixing of modes had very unpleasant performance consequences for files with a lot of timesteps and/or a lot of variables because it required **_all_** file metadata to be loaded on Open(), even if you were going to use BeginStep/EndStep and only access it timestep by timestep.  The new requirement for BP5 was that if you used Mode::Read, you had to use BeginStep/EndStep and you could only do InquireVariable() between the Begin/End pairs.  If you used Mode::ReadRandomAccess you were not allowed to use BeginStep/EndStep, but you could read any variable with SetStepSelection (and you could do InquireVariable() at any time after Open.  Behavior didn't change for BP3/4 in release 2.8, and for those engines ReadRandomAccess was equivalent to Read.   However, ADIOS 2.9 made the BP5 engine the default, potentially breaking code that used the older style.  If you were using the C++ interface, calling InquireVariable outside the Begin/End pair would have gotten you a helpful and informational exception that informed you of this change, but unfortunately the C interface helpfully swallows exceptions.  Sorry about that.  (And sorry that the examples didn't get updated, we just realized that in a meeting earlier this week.)

So, there are multiple options for going forward.  You can explicitly set the ADIOS file engine that you are using to "BP4" to go back to the old behavior (probably not recommended), or you can change the open() parameter to specify `adios2_mode_read_random_access` instead of `adios2_mode_read` (probably the right answer, as long as your files aren't massive), or you can leave the open mode as is, use Begin/EndStep, but only do InquireVariable inside those pairs.  Hopefully one of these works for you.

Nice wombat BTW.

**Comment by manauref** [comment]
Thanks @eisenhauer.
I can give the second or third option. Regarding the second: Any idea what "files aren't massive" mean? can you give an order of magnitude over which this might cause problems?

**Comment by eisenhauer** [comment]
It's hard to say exactly, but the concern is with metadata size (not data size), so it's with the total number of Put()s, each of which generates a metadata entry.  With BP4 we saw issues when writing hundreds of variables from thousands of ranks for thousands of timesteps, but if your situation keeps those the product of variables, ranks and timesteps gets above six or 8 decimal digits there might be cause for concern.  Less than that, probably not.   (But if you do have a really massive case, that's where things get interesting for us, so we're happy to help.)

**Comment by manauref** [comment]
Sounds good. I'll let you know when we hit that limit, may be soonish.

btw, I can confirm that the other two options you suggested work. I'm happy to submit an example for the examples folder if you'd like.

**Comment by eisenhauer** [comment]
> btw, I can confirm that the other two options you suggested work. I'm happy to submit an example for the examples folder if you'd like.

Glad the other options work.  Appreciate the offer on the examples, but we've got someone assigned, so probably easiest to let them plow through.
