### ISSUE TITLE
BPChangingShapeWithinStep.Multiblock.BP3 and BP4 tests are flaky

### ISSUE THREAD

**Issue by vicentebolea** [ornladios/ADIOS2#3897]
It fails in Many builds as shown here:

https://open.cdash.org/queryTests.php?project=ADIOS&begin=2023-10-26&end=2023-11-06&filtercount=1&showfilters=1&field1=testname&compare1=63&value1=Engine.BP.*%2FBPChangingShapeWithinStep.MultiBlock%2F*.BP3.MPI

![Screenshot from 2023-11-06 18-02-46](https://github.com/ornladios/ADIOS2/assets/939798/be1ea8ef-8ce0-4d20-8787-22e7cacc7e30)

**Comment by vicentebolea** [comment]
@eisenhauer do you know what can be causing this issue?

**Comment by eisenhauer** [comment]
In a word, no, I have no idea.  This test is kinda new.  @pnorbert created it in April.  That it's only failing BP3/4 is odd because those engines aren't really undergoing development currently.  The tests are timing out, which is odd behavior for such a simple test, BUT they run differently on different platforms depending upon whether BLOSC, MGARD and ZFP are available.  I.E. it'll run the same simple subtest with "none" and then with each compressor that is available.  Maybe there's a new problem with one of those compressors?

In a separate question, we no longer seem to be building testing by default.  I.E. BUILD_TESTING, which used to default to on, now defaults to off.  Was that deliberate and maybe I just missed the discussion?

**Comment by vicentebolea** [comment]
> In a separate question, we no longer seem to be building testing by default. I.E. BUILD_TESTING, which used to default to on, now defaults to off. Was that deliberate and maybe I just missed the discussion?

We talked this in one of the adios2 weekly meetings a three weeks ago. The change was added in https://github.com/ornladios/ADIOS2/pull/3820. The rationale was that most of the users do not need/want to run the tests.

**Comment by vicentebolea** [comment]
> Maybe there's a new problem with one of those compressors

Maybe, another hint is that we do not see the problem with BP5

**Comment by eisenhauer** [comment]
Looking at the no-test-repeats CDash output, I'd suspect that MGARD is the problem...
https://open.cdash.org/viewTest.php?onlyfailed&buildid=9130458
