### ISSUE TITLE
ADIOS2 cannot be compiled on Titan with Lustre dependency

### ISSUE THREAD

**Issue by lwan86** [ornladios/ADIOS2#393]
#error "size_t could not be mapped to a MPI Type"

**Comment by chuckatkins** [comment]
Can you give some details on how to reproduce this?  i.e. what's the module configuration, what's the configure arguments, compilers used, etc.?

**Comment by williamfgc** [comment]
PrgEnv-gnu/5.3.0 , SIZE_MAX can't be found on climits or cstdlib

**Comment by williamfgc** [comment]
module load cmake3/3.6
module load PrgEnv-gnu/5.3.0
mkdir build
cmake ../ADIOS2
make -j 16

**Comment by lwan86** [comment]
> module list
Currently Loaded Modulefiles:
  1) eswrap/1.3.3-1.020200.1280.0           8) modulator/1.2.0                       15) cray-libsci/16.11.1                   22) dvs/2.5_0.9.0-1.0502.2188.1.113.gem
  2) craype-network-gemini                  9) hsi/5.0.2.p1                          16) udreg/2.3.2-1.0502.10518.2.17.gem     23) alps/5.2.4-2.0502.9774.31.12.gem
  3) cray-mpich/7.5.2                      10) DefApps                               17) ugni/6.0-1.0502.10863.8.28.gem        24) rca/1.0.0-2.0502.60530.1.63.gem
  4) craype-interlagos                     11) cmake3/3.9.0                          18) pmi/5.0.12                            25) atp/2.0.5
  5) lustredu/1.4                          12) gcc/4.8.1                             19) dmapp/7.0.1-1.0502.11080.8.74.gem     26) PrgEnv-intel/5.2.82
  6) xalt/0.7.5                            13) intel/17.0.0.098                      20) gni-headers/4.0-1.0502.1085

**Comment by pnorbert** [comment]
The problem seems to come from lustre api found and allowed. This is in 
lwang86/adios2.git, branch lustre-transport 
There is a cmake/FindLustre.cmake that finds (but does not test) lustre/lustreapi.h and liblustre.a
If that branch is forced not to have lustre (-DADIOS2_USE_Lustre=OFF), it passes the build of the core classes. If it is enabled, compiling core/Attribute.cpp will fail. Nothing there and in the included files refer or use lustre. 
Tried to copy the lustre api over to a VM, where cmake finds it. But it does not disturb the build process there. Both titan and vm uses cmake 3.9.0, but gcc is 4.9.3 vs 6.2.0.
Can't figure out what actually breaks the build.

**Comment by williamfgc** [comment]
the lustre headers on Titan are pretty outdated and they require the -fpermissive flag from GNU. Hacked a version in my lustre-transport branch that won't make it to master. Closing this.
