### ISSUE TITLE
`adios2-config` missing from Conda installation

### ISSUE THREAD

**Issue by kshitij-v-mehta** [ornladios/ADIOS2#4151]
I am installing adios2 using Conda on a local Linux box. `adios2-config` is missing from the installed adios2 package. Tested with versions 2.9 and 2.10 on a local Debian box.

**Comment by vicentebolea** [comment]
This is correct and it is by design. We encountered several problems with the way that adios2-config script is generated (it reverses engineer cmake outputs), this causes so many issue at conda users and CI, for that reason we decided to let it go in Conda.

https://github.com/conda-forge/adios2-feedstock/blob/e96fa60c77a055cfbe1389f43720c18ad2f74de2/recipe/build-libadios.sh#L47
