### ISSUE TITLE
Unexpected name truncation at a round opening bracket

### ISSUE THREAD

**Issue by sergeylesnik** [ornladios/ADIOS2#4202]
**Bug Description**
If there is a round opening bracket "(" in the string given to DefineVariable, the name of the written variable in the .bp file is truncated at the location of the bracket. Such names are common within OpenFOAM.

**To Reproduce**
1. Change a line in the heatTransfer tutorial according to this diff:

```
diff --git a/examples/simulations/heatTransfer/write/IO_adios2.cpp b/examples/simulations/heatTransfer/write/IO_adios2.cpp
index 1eba7211e..fc87f6ae3 100644
--- a/examples/simulations/heatTransfer/write/IO_adios2.cpp
+++ b/examples/simulations/heatTransfer/write/IO_adios2.cpp
@@ -43,7 +43,7 @@ IO::IO(const Settings &s, MPI_Comm comm)
     }
 
     // define T as 2D global array
-    varT = bpio.DefineVariable<double>("T",
+    varT = bpio.DefineVariable<double>("ddt0(thermo:psi,p)/boundaryField/wallsPilots/value",
                                        // Global dimensions
                                        {s.gndx, s.gndy},
                                        // starting offset of the local array in the global space
```
2. Compile and execute like in the corresponding ReadMe
```
mpirun -np 12 ./build/write/adios2_simulations_heatTransferWrite heat_file.xml heat.bp 4 3 5 10 10 10
```
3. List the result: `bpls heat.bp` with the output:
```
  double   ddt0  11*{20, 30}
```
**Expected behavior**
The output of bpls should be:
```
  double  ddt0(thermo:psi,p)/boundaryField/wallsPilots/value  11*{20, 30}
```
Replacing the opening parenthesis with a curly bracket delivers an expected result.

**Desktop**
 - OS/Platform:Ubuntu 20.04, workstation
 - Build gcc 9.4.0, cmake version 3.28.1, ADIOS2 current master (8cd2d948199)

**Comment by eisenhauer** [comment]
Ah, yes.  That will be a property of BP5 marshaling (in the BP5 file engine and in SST) because its use of FFS.  It's possible that we can avoid this in a future release, but at present there would be no workaround other than avoiding the open paren '(' in variable names or using the BP4 engine.

Longer story:  ADIOS variable names are pretty directly encoded into FFS structure field names in BP5 metadata.  FFS uses paren-enclosed values in field names to activate some functionality that isn't used or required for the way BP5 uses FFS.  In order to avoid using the reserved '(' character, we'd have to do something like base64-encode the ADIOS variable name in BP5 metadata.  Possible of course, but would introduce an incompatibility between old and new metadata versions, so at a minimum not something we could put in a minor release.

**Comment by sergeylesnik** [comment]
Thank you for the prompt response. It looks like we'll switch to BP4 by now and wait for a solution. Replacing "(" might be also an option but only a temporary one.

**Comment by eisenhauer** [comment]
There may be a backwards-compatible solution for BP5, but I've got to do some more checking...  But with the current code base using BP4 is probably the easy path.  I'll tag this issue in any PR that changes things.

**Comment by eisenhauer** [comment]
You might try PR #4203, but I think it corrects this problem...

**Comment by olesenm** [comment]
For the moment, I think it is okay if we just prefilter to remove the problematic characters:
```
auto i = name_.find_first_of("()");
if (i != std::string::npos)
{
    fileName cleaned(name_);
    const auto len = cleaned.size();
    cleaned[i] = '_';
    ++i;
    for (; i < len; ++i)
    {
        if (cleaned[i] == '(' || cleaned[i] == ')')
        {
            cleaned[i] = '_';
        }
    }
    return cleaned;
}
```
I hope there aren't any more hidden surprises...

**Comment by eisenhauer** [comment]
Your preference...   I'll go ahead and close this then.

**Comment by olesenm** [comment]
> Your preference... I'll go ahead and close this then.

Sounds good. You are now aware of the potential issue (and have a pull-request to address), and we have a workaround that is painless enough.
