### ISSUE TITLE
adios2::Variable metadata going out of scope with SST engine

### ISSUE THREAD

**Issue by stevenwalton** [ornladios/ADIOS2#740]
I have a SST reader where I am updating a map `map<string, adios2::Variable<double>>` (`sstReadVars`) and after the stream ends I am writing the data to a bp file. 

My problem is that the metadata, specifically the Shape, gets overwritten by the time I can write to a bp file. This does not matter if my `sstReader.Close()` is after I am done reading from the stream (current location) or after I write to the bp file. The data always gets overwritten in the same place, after the while condition breaks (`while(sstReader.BeginStep() == adios2::StepStatus::OK)`). The values for the metadata seem to be reinitialized with garbage. Data within `adios2::Params` (`variables`) appears to maintain metadata after the close. 

I have included my reader code below and commented the code to be relevant to the issue at hand.

I can get around this by creating different vectors or maps to hold that data, this is also noted in comments of relevant lines. As is, the code below produces the correct output. Comments of what I expected to be able to do are left in.

```
#include <iostream>
#include <vector>
#include <stdlib.h>


#include <adios2.h>
#include <mpi.h>

int main(int argc, char* argv[])
{
    MPI_Init(&argc, &argv);
    int rank, size;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);
    adios2::ADIOS adios(MPI_COMM_WORLD, adios2::DebugON);

    std::size_t iteration = 0;
    //**********************************************************//
    //                  Receive over SST 
    //**********************************************************//
    std::map<std::string, std::vector<double>> vars;
    adios2::IO sstRIO  = adios.DeclareIO("sstIO");
    sstRIO.SetEngine("SST");
    std::string fName = "mySSTStream";
    adios2::Engine sstReader = sstRIO.Open(fName, adios2::Mode::Read);

    std::map<std::string, adios2::Variable<double>> sstReadVars;  // What I want to call for my metadata
    std::map<std::string, adios2::Params> variables;
    std::map<std::string, adios2::Params>::iterator it;
    std::map<std::string, std::vector<std::size_t>> myShape; // Needed to keep shape

    while(sstReader.BeginStep() == adios2::StepStatus::OK)
    {
        variables = sstRIO.AvailableVariables();
        for ( auto elem : variables )
        {
            std::string name = elem.first;
            sstReadVars[name] = sstRIO.InquireVariable<double>(name);
            vars[name];
            sstReader.Get<double>(sstReadVars[name], vars[name]);
            myShape[name] = sstReadVars[name].Shape(); // Line needed to maintain metadata
        }
        sstReader.EndStep();
        iteration++;
        // Metadata is correct here
    }
    // Metadata is out of scope HERE. Metadata is garbage
    // variables metadata is correct here
    sstReader.Close();

    //**********************************************************//
    //                  Write to new bp file
    //**********************************************************//
    std::string file = "foo.bp";

    adios2::IO bpWIO = adios.DeclareIO("BPWrite");
    bpWIO.SetEngine("BPFile");
    std::vector<adios2::Variable<double>> bpWriteVars;
    for ( auto elem : variables )
    {
        std::string name = elem.first;
        //std::size_t size = sstReadVars[name].Shape().size(); // Results in correct size
        std::size_t size = myShape[name].size();

        //std::vector<std::size_t> globalDims = sstReadVars[name].Shape(); // How I wanted to get my dimensions. Results in garbage values but the resultant vector is the correct size

        std::vector<std::size_t> offset(size, 0);

        //std::vector<std::size_t> localDims = sstReadVars[name].Shape();  // Again results in bad data

        bpWriteVars.emplace_back(
                bpWIO.DefineVariable<double>(name,
                                             myShape[name],//globalDims,
                                             offset,
                                             myShape[name]));//localDims));
    }
    adios2::Engine bpWriter = bpWIO.Open(file, adios2::Mode::Write);
    bpWriter.BeginStep();

    // variables maintains proper metadata
    for ( auto i = 0; i < variables.size(); ++i )
    {
        std::string name = it -> first;
        bpWriter.Put<double>(bpWriteVars[i], vars[name].data());
    }
    bpWriter.EndStep();
    bpWriter.Close();
    // Can place sstReader.Close() here with no change 

    MPI_Finalize();
    return 0;
}
```
Stream is being produced my cloverleaf example in https://github.com/stevenwalton/ascent and being run on Ubuntu 16.04.

**Comment by eisenhauer** [comment]
IMHO, this code relies upon things that it shouldn't rely upon.  In particular, this reader code will break if the writer doesn't happen to write the same set of variables on each timestep.  It will also break if the written variables don't happen to be written with the same shape in each timestep.  It relies upon an artifact of the implementation of some engines.  Generally variables and their metadata are only valid after EndStep and until the next BeginStep.  However, some engines don't clear out the variable set in the IO until they have new data, so they will happen to leave variables and metadata from the last timestep around if the BeginStep returns other than StepStatus::OK.  (If it returns StepStatus::OK, the previous timestep's variables are always wiped.)  This code then assumes that the metadata from that last timestep can be reasonably applied to all prior timesteps.  That's not sensible.

So, we could change SST to behave like the other engines, but frankly, I think their behaviour isn't worth standardizing.  I'd rather tell folks that they can rely upon metadata being valid from one successful BeginStep until the next BeginStep, and not also add "and yeah, if BeginStep exits with other than an OK condition, then that metadata from the last present timestep doesn't actually get released at all, so you can go ahead and use it."  A general-purpose "stream copy" operator can't be written the way this one is, because a stream with any variability in it would break this.  A proper implementation would likely integrate those loops, reading and writing in the same pass rather than saving the data, assuming that every variable was written in every timestep and with the same global dimensions every time.

**Comment by pnorbert** [comment]
Proposed solution:
1. Let's keep SST as it is: when BeginStep() is called, the user indicates that there is no need for the variables of the current step, which actually became "previous" step because EndStep() was called.

2. Let's have an extra user function to return a (vector of) VarInfo struct describing variables, which gives back a data structure owned by the user:

struct VarInfo holds: name, type (string), and Shape (Dims)
std::vector<VarInfo> VarsInfo (const std::vector<std::string> varNames) const;
and an overloaded version with std::string input.

**Comment by eisenhauer** [comment]
I'm going to close this issue because the proposed resolution is an enhancement of the API to provide a different interface to read data, not a modification to SST or other engines.  I'd suggest submitting another issue if we want to go forward with this.
