### ISSUE TITLE
SST with multiple consumers is not working anymore

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#741]
This did work before. One producer and two consumers. 

The a->b->c pipeline works fine in the heat transfer example
`mpirun -n 4 simulation/heatSimulation_adios2 sim 2 2 50 50 10 100 : -n 2 ../cpp/heatAnalysis sim.bp analysis.bp 2 1 : -n 1 ../cpp/heatVisualization analysis.bp`

But a-> (b & c) with two readers of the same stream hangs:

```
mpirun -n 4 simulation/heatSimulation_adios2 sim 2 2 50 50 10 100 : -n 2 ../cpp/heatAnalysis sim.bp analysis.bp 2 1 : -n 1 ../cpp/heatVisualization sim.bp
Process decomposition  : 2 x 2
Array size per process : 50 x 50
Number of output steps : 10
Iterations per step    : 100
Simulation step    0: initialization
```

After the fix we also need a test for this to make sure it does not go away.

**Comment by eisenhauer** [comment]
BTW, for things like this it's handy to be able to specify engine parameters on the command line, for which they'd have to be parsed from a string.  I have some code that does this that I use in some SST tests to avoid having to have lots of executables or lots of .xml files.  But it would be better to have a more broadly visible ADIOS2 function that could be used for this.

**Comment by pnorbert** [comment]
I was not aware that I had to provide a parameter for that. That makes
sense but I don't remember using one at the ECP demo in February.
Thanks

**Comment by eisenhauer** [comment]
Well, it *might* work without one, but it might not.  The writer will always accept a second client, but the parameter guarantees that it will be there to accept it.  If the writer is going to run for a long time, you probably don't need it because the 2nd reader will likely start before it dies.   But if the writer might complete quickly, it's a good idea to tell it to wait.  (I'm working on some tests for more of these cases, but they are probably going to be long-running tests for these sorts of reasons...)

**Comment by eisenhauer** [comment]
This is fixed again.
