### ISSUE TITLE
DataMan StepStatus

### ISSUE THREAD

**Issue by stevenwalton** [ornladios/ADIOS2#749]
I have noticed in the examples that DataMan is not using BeginStep and EndStep. Going through the examples I noticed that it is only grabbing a single time step and that to read multiple time steps that the reader needs to be looped. This has led to to an inability to use the same scheme for looping over steps as in SST and determining the final step automatically.

Eg:
```
while ( myReader.BeginStep() == adios2::StepStatus::OK )
{
   ... get data ...
   myReader.EndStep();
}
myReader.Close();
```
With the DataMan engine this code quickly exits, not reading any data.

Could we add functionality for DataMan to return a StepStatus and act similar to SST in this fashion?

**Comment by JasonRuonanWang** [comment]
#742

**Comment by JasonRuonanWang** [comment]
@stevenwalton The latest master should work now. But you will need to use "p2p" mode rather than "subscribe". The publish-subscribe mode is designed such that the writer and reader are always running regardless the stream is ended or not. Even a writer ends, the reader should still listen to the same port and wait for another potential writer to start.

In the "p2p" mode a writer and a reader is strictly coupled, so the read finishes when the writer finishes.
