### ISSUE TITLE
SST Errors With Scaling 

### ISSUE THREAD

**Issue by stevenwalton** [ornladios/ADIOS2#810]
I've been trying to test my Ascent code (an ECP project) on Rhea and been finding some interesting results. When I was trying to start "small" and set my number of writer processors to 64 and noticed that I wouldn't always get results back and the SST readers would crash.

So I started small and worked my way up. I would submit only the writer job and I had two different readers that I would specifically run on the login node (logged into specific node to avoid load balancing).  The readers only use one processor (minimizing variables, and load to login node). 

With the writer having 2,4, 8, 16 processors running I can get data back. In the case of 32 processors my second reader (one that handled less data) exited correctly and the first reader hangs. The behavior I was getting from the 64 processors is a report back from qsub that my program timed out and I would have no data from the readers (also submitted with the job), which would write after the final iteration they received.

These readers use `StepStatus` to check if it should move on
```
while ( sstReader.BeginStep(adios2::StepMode::NextAvailable) == adios2::StepStatus::OK)
```

ABOUT [RHEA](https://www.olcf.ornl.gov/for-users/system-user-guides/rhea/system-overview/):
512 Nodes with [2x] Intel® Xeon® E5-2650 @ 2.0 GHz – 8 cores, 16 HT and 128GB RAM.

Could this be connected to core count?

Side note: I am also writing BPFiles during this time, and have no problem with them. Even at the 64 processor level.

**Comment by stevenwalton** [comment]
Update: I tried running on Rhea with 64 processors and using the BP marshaling method, instead of FFS. I get the same problem, where the readers hang. 

I have even tried to set a short timeout, such as:
```
while ( sstReader.BeginStep(adios2::StepMode::NextAvailable, 60) == adios2::StepStatus::OK)
```

**Comment by eisenhauer** [comment]
None of those things (marshaling or timeout) are likely to influence a problem with hanging.  The marshaling method only impacts the format of the data that is exchanged, not the control system that manages its exchange.  And SST does not attempt to implement a timeout now.  (In general timeouts like the one proposed for BeginStep are problematic.  The issue is if a timestep arrives near the end of the timeout expiration period, a reader rank might see the timestep arrive either just before or just after the timeout expires. So you either have the possibility of each rank seeing different set of timesteps, or you do extra synchronization just to support this feature (so that you can have centralized timekeeping, etc.)

The hanging issue is more likely related to a race condition in the distributed protocol that implements data exchange in SST, or a problem in the network layers that underlay SST (such as the ENET reliable UDP layer).   It's pretty natural for the number of ranks to have an impact on these things because they change timing, resource utilization, etc.  The BP file writer is really too simple to break like that.

**Comment by stevenwalton** [comment]
@JasonRuonanWang I just tested DataMan with one write processor on Rhea and found that I got my file writing out from the last time step. 

Mark had suggested that maybe some of the blocks contain no data within them and that might be causing a problem, since it appears to be both SST and DataMan. I can test this tomorrow if you and @eisenhauer think this might be an issue.

**Comment by JasonRuonanWang** [comment]
Even if there is any blocks containing no data, as long as you allocated the buffer and use this valid buffer to call the Put() function, there should be still either zeros or NANs or randoms numbers. I don't think this will cause any real problems.

We can test tomorrow.

**Comment by eisenhauer** [comment]
This is an old issue from well before the first release and there have been lots of updates, timeout implementation, and more extensive testing at scale since then.  I'm closing this issues as unlikely to be relevant to current master status.  @stevenwalton , if you have more current issues (or if this is actually still relevant), please let us know.
