### ISSUE TITLE
Build error on Summit

### ISSUE THREAD

**Issue by suchyta1** [ornladios/ADIOS2#814]
I'm trying to build the master branch on Summit with the GNU compilers and getting a build error when I do so. I've attached the build log.
[summit-build.log](https://github.com/ornladios/ADIOS2/files/2310468/summit-build.log)

**Comment by suchyta1** [comment]
Versions 2.1.0 and 2.2.0 build OK though.

**Comment by pnorbert** [comment]
Does cmake have a check for complex long doubles? Then we could solve this problem at compile time. Otherwise we need to remove this type.

**Comment by chuckatkins** [comment]
The build is failing with an internal compiler error, which means a compiler bug is hit, not adios.  That being said, we might be able to work around it.  Wrt  long double though, i'd vote to remove it entirely since it's a nonstandard inconsistent type.  Float and double are 32 and 64 bit floating point values respectively.  Long double though is often 96 bit, sometimes 128bit, etc.  That's probably a discussion best left to the dev meetings though.  In the meantime I will see if I can work around the compiler bug.

**Comment by williamfgc** [comment]
https://gcc.gnu.org/wiki/Ieee128PowerPC there is a flag to enable long double on GCC for PowerPC. Not sure if it will solve the issue on Summit

**Comment by suchyta1** [comment]
Thanks, I'll try it out.

**Comment by suchyta1** [comment]
Sorry for the delay, but yes, this fix worked for me.

**Comment by ax3l** [comment]
FWIW, GCC 7.4.0, 8.1.0, 8.1.1, 9.1.0 on Summit do not have the same internal compiler error. So this seams to be fixed in newer versions of GCC.
