### ISSUE TITLE
SST has a 

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#913]
SST has the same scalability issue that InsituMPI had in 
Fix scalability bottleneck in InSituMPIReader PR #863

"Currently, the reader receives and deserializes messages from each writer one by one. This design is limiting the scalability in terms of the number of writers per reader. Need to change the behavior to a bulk receive followed by a bulk deserialization."

ffs_marshal.c:
```
static SstStatusValue WaitForReadRequests(SstStream Stream)
{
    struct FFSReaderMarshalBase *Info = Stream->ReaderMarshalData;

    for (int i = 0; i < Stream->WriterCohortSize; i++)
    {
        if (Info->WriterInfo[i].Status == Requested)
        {
            SstStatusValue Result =
                SstWaitForCompletion(Stream, Info->WriterInfo[i].ReadHandle);
            if (Result == SstSuccess)
            {
                Info->WriterInfo[i].Status = Full;
                DecodeAndPrepareData(Stream, i);
            }
            else
            {
                CP_verbose(Stream, "Wait for remote read completion failed, "
                                   "returning failure\n");
                return Result;
            }
        }
    }
    CP_verbose(Stream, "All remote memory reads completed\n");
    return SstSuccess;
}
```
Similarly, this needs to be checked for BP marshalling.

**Comment by pnorbert** [comment]
Oh, quite the opposite. SST readers may benefit from overlapping waits and deserializations, which in the above PR was slowing down the __Writer__ side. In case of SST, the Writer side is progressing asynchronously, so this would not be an issue.

**Comment by chuckatkins** [comment]
@eisenhauer is this still an issue in current SST?

**Comment by eisenhauer** [comment]
The short answer is yes, but the longer answer is more complex.  At some point, we probably need to have a more serious look at the reader side for BP marshalling.  We're currently doing a remote memory read for each variable (for the default BP marshalling), and that is probably bad, at least when we have a lot of variables and are our read density (percentage of writer data that a reader might need) is high.  But it might actually be beneficial if density is low and variables are few.  We also know writer-side BP marshalling is non-optimal (extra MPI_Gather ops in the metadata aggregation code rather than leveraging the ones that SST needs to do).  Generally I think action on this has awaited 1) someone willing to tackle the BP aspects and 2) a better characterization of how important all this is (I.E. performance analysis including parameter sweeps across variable counts, data sizes and communication patterns).   Maybe the thing to do would be to kill this issue (which is rather specific and badly named) and open something reminding us to accomplish the marshalling analysis and to rewrite according to the results.

**Comment by eisenhauer** [comment]
As per the prior comment, I'm going to close this issue as I am moving forward with BP rewrites...
