### ISSUE TITLE
Getting errors with heat2d example in Adios tutorial 

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#943]
Tried to update heat2d (fortran version) in the tutorial (adiosvm) to use the most recent version of Adios2. My update is making some error with InSituMPI at the last step:
```
ERROR: InSituMPI engine only allows for 1 PerformGets() per step.
```
I have checked in my changes to the ADIOSVM repository (my changes are [here](https://github.com/pnorbert/adiosvm/commit/ba5eeb37e35a7d6b150a09fc197aae7bec643f20))

I am getting similar errors in other code too (XGC coupling codes).

**Comment by williamfgc** [comment]
Hi @jychoi-hpc please check against istatus, not ierr after begin_step.

**Comment by jychoi-hpc** [comment]
Great!! It works now.
Then, now we need to check both ierr and istatus?

**Comment by jychoi-hpc** [comment]
Before this, we checked "adios2_step_status_end_of_stream" at the end of stream (adios2_end_step). Now we should check after calling "adios2_begin_step". Is it also right?

**Comment by williamfgc** [comment]
hi @jychoi-hpc , the check for status has always been after `adios2_begin_step` ,`adios2_end_step` doesn't check step status, it basically executes puts and gets since the step is signaled ready at `adios2_begin_step`.  Just like `MPI_IRecv` there is a flag for actual errors (`ierr`), and a `MPI_Request` that can be checked with a `MPI_Status`, thus a flag for status.  `ierr` is for user (invalid arguments) and unexpected runtime errors (bad_allocation, system io failure, etc.) . Status is basically just checking if the stream is ready or not or if we reached the end of it within normal execution `ierr = adios2_error_none`.  Yes, the recommended and ideal way is to check both, but Fortran users hardly ever check for ierr. Hope this helps. Thanks!

**Comment by williamfgc** [comment]
@jychoi-hpc let me know if this is still an issue, otherwise let's close it. In Fortran, MPI request, status and ierr are all integers as well. Thanks.

**Comment by pnorbert** [comment]
This has been fixed in the tutorial example.
