### ISSUE TITLE
Test for ADIOS1Writer output warning messages

### ISSUE THREAD

**Issue by chuckatkins** [ornladios/ADIOS2#97]
The ADIOS1Writer tests all output the following warning message:
```
WARN : Unable to write /__adios__/timer_labels_1, continuing
```

**Comment by pnorbert** [comment]
The warning is because the adios1 engine has to delete all variable definitions at every advance to ensure new definitions can be used in consecutive writes. This comes from the difference between adios1 and adios2, namely that array sizes are not defined by other variables anymore but actual values. As a consequence though, the timer variables are deleted as well after the first write and they are not found in consecutive steps. They are defined inside adios1 transport methods once and not re-created afterwards. This is a harmless bug, no user data is affected, just a strange warning message on screen.
