### ISSUE TITLE
SST: CM_INTERFACE as an engine parameter

### ISSUE THREAD

**Issue by keichi** [ornladios/ADIOS2#997]
Hi, I want to run adios_reorganize with SST for both input and output, each using a different network interface. I can set CM_INTERFACE to select which NIC to use, but it doesn't work if there are multiple engines like in this situation since environment variables are global. Can we have CM_INTERFACE as an engine parameter?

**Comment by eisenhauer** [comment]
Keichi, yes, in principal.  In practice that will take a bit of juggling and rearrangement as there are several layers of software to penetrate.

Sent from my iPhone

On Nov 11, 2018, at 10:05 AM, Keichi Takahashi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I want to run adios_reorganize with SST for both input and output, each using a different network interface. I can set CM_INTERFACE to select which NIC to use, but it doesn't work if there are multiple engines like in this situation since environment variables are global. Can we have CM_INTERFACE as an engine parameter?

**Comment by eisenhauer** [comment]
Fix merged.  Still need to document.
